<!DOCTYPE html>
<html lang="en" xml:lang="en">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 3 Scoring | DRAFT: ReCentering Psych Stats: Multivariate Modeling</title>
  <meta name="description" content="This is an open-access, book-in-progress. My goal in offering it is to re-center the materials used in training statistics and research methods in graduate and post-graduate psychology programs." />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 3 Scoring | DRAFT: ReCentering Psych Stats: Multivariate Modeling" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is an open-access, book-in-progress. My goal in offering it is to re-center the materials used in training statistics and research methods in graduate and post-graduate psychology programs." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 3 Scoring | DRAFT: ReCentering Psych Stats: Multivariate Modeling" />
  
  <meta name="twitter:description" content="This is an open-access, book-in-progress. My goal in offering it is to re-center the materials used in training statistics and research methods in graduate and post-graduate psychology programs." />
  

<meta name="author" content="Lynette H Bikos, PhD, ABPP" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="scrub.html"/>

<script src="libs/header-attrs-2.6/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="css/style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./"><strong>ReCentering Psych Stats: Multivariate Modeling</strong><br>by Lynette H Bikos, PhD, ABPP</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#copyright-with-open-access"><i class="fa fa-check"></i>Copyright with Open Access</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="ReCintro.html"><a href="ReCintro.html"><i class="fa fa-check"></i><b>1</b> Introduction</a>
<ul>
<li class="chapter" data-level="1.1" data-path="ReCintro.html"><a href="ReCintro.html#what-to-expect-in-each-chapter"><i class="fa fa-check"></i><b>1.1</b> What to expect in each chapter</a></li>
<li class="chapter" data-level="1.2" data-path="ReCintro.html"><a href="ReCintro.html#if-you-are-new-to-r"><i class="fa fa-check"></i><b>1.2</b> If You are New to R</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="ReCintro.html"><a href="ReCintro.html#r-hygiene"><i class="fa fa-check"></i><b>1.2.1</b> R Hygiene</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="ReCintro.html"><a href="ReCintro.html#maximizing-learning-by-accessing-all-the-resources"><i class="fa fa-check"></i><b>1.3</b> Maximizing Learning by Accessing all the Resources</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="dataprep.html"><a href="dataprep.html"><i class="fa fa-check"></i>DATA PREP</a></li>
<li class="chapter" data-level="2" data-path="scrub.html"><a href="scrub.html"><i class="fa fa-check"></i><b>2</b> Scrubbing</a>
<ul>
<li class="chapter" data-level="2.1" data-path="scrub.html"><a href="scrub.html#navigating-this-lesson"><i class="fa fa-check"></i><b>2.1</b> Navigating this Lesson</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="scrub.html"><a href="scrub.html#learning-objectives"><i class="fa fa-check"></i><b>2.1.1</b> Learning Objectives</a></li>
<li class="chapter" data-level="2.1.2" data-path="scrub.html"><a href="scrub.html#planning-for-practice"><i class="fa fa-check"></i><b>2.1.2</b> Planning for Practice</a></li>
<li class="chapter" data-level="2.1.3" data-path="scrub.html"><a href="scrub.html#readings-resources"><i class="fa fa-check"></i><b>2.1.3</b> Readings &amp; Resources</a></li>
<li class="chapter" data-level="2.1.4" data-path="scrub.html"><a href="scrub.html#packages"><i class="fa fa-check"></i><b>2.1.4</b> Packages</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="scrub.html"><a href="scrub.html#workflow-for-scrubbing-and-scoring"><i class="fa fa-check"></i><b>2.2</b> Workflow for Scrubbing and Scoring</a></li>
<li class="chapter" data-level="2.3" data-path="scrub.html"><a href="scrub.html#research-vignette"><i class="fa fa-check"></i><b>2.3</b> Research Vignette</a></li>
<li class="chapter" data-level="2.4" data-path="scrub.html"><a href="scrub.html#working-the-problem"><i class="fa fa-check"></i><b>2.4</b> Working the Problem</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="scrub.html"><a href="scrub.html#intravenous-qualtrics"><i class="fa fa-check"></i><b>2.4.1</b> intRavenous Qualtrics</a></li>
<li class="chapter" data-level="2.4.2" data-path="scrub.html"><a href="scrub.html#about-the-rate-a-recent-course-survey"><i class="fa fa-check"></i><b>2.4.2</b> About the <em>Rate-a-Recent-Course</em> Survey</a></li>
<li class="chapter" data-level="2.4.3" data-path="scrub.html"><a href="scrub.html#the-codebook"><i class="fa fa-check"></i><b>2.4.3</b> The Codebook</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="scrub.html"><a href="scrub.html#scrubbing"><i class="fa fa-check"></i><b>2.5</b> Scrubbing</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="scrub.html"><a href="scrub.html#tools-for-data-transcodmation"><i class="fa fa-check"></i><b>2.5.1</b> Tools for Data Transcodmation</a></li>
<li class="chapter" data-level="2.5.2" data-path="scrub.html"><a href="scrub.html#inclusion-and-exclusion-criteria"><i class="fa fa-check"></i><b>2.5.2</b> Inclusion and Exclusion Criteria</a></li>
<li class="chapter" data-level="2.5.3" data-path="scrub.html"><a href="scrub.html#renaming-variables"><i class="fa fa-check"></i><b>2.5.3</b> Renaming Variables</a></li>
<li class="chapter" data-level="2.5.4" data-path="scrub.html"><a href="scrub.html#downsizing-the-dataframe"><i class="fa fa-check"></i><b>2.5.4</b> Downsizing the Dataframe</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="scrub.html"><a href="scrub.html#steps-toward-the-apa-style-write-up"><i class="fa fa-check"></i><b>2.6</b> Steps Toward the APA Style Write-up</a>
<ul>
<li class="chapter" data-level="2.6.1" data-path="scrub.html"><a href="scrub.html#methodprocedure"><i class="fa fa-check"></i><b>2.6.1</b> Method/Procedure</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="scrub.html"><a href="scrub.html#practice-problems"><i class="fa fa-check"></i><b>2.7</b> Practice Problems</a>
<ul>
<li class="chapter" data-level="2.7.1" data-path="scrub.html"><a href="scrub.html#problem-1-rework-the-chapter-problem"><i class="fa fa-check"></i><b>2.7.1</b> Problem #1: Rework the Chapter Problem</a></li>
<li class="chapter" data-level="2.7.2" data-path="scrub.html"><a href="scrub.html#problem-2-use-the-rate-a-recent-course-survey-choosing-different-variables"><i class="fa fa-check"></i><b>2.7.2</b> Problem #2: Use the <em>Rate-a-Recent-Course</em> Survey, Choosing Different Variables</a></li>
<li class="chapter" data-level="2.7.3" data-path="scrub.html"><a href="scrub.html#problem-3-other-data"><i class="fa fa-check"></i><b>2.7.3</b> Problem #3: Other data</a></li>
</ul></li>
<li class="chapter" data-level="2.8" data-path="scrub.html"><a href="scrub.html#bonus-track"><i class="fa fa-check"></i><b>2.8</b> Bonus Track:</a>
<ul>
<li class="chapter" data-level="2.8.1" data-path="scrub.html"><a href="scrub.html#importing-data-from-an-exported-qualtrics-.csv-file"><i class="fa fa-check"></i><b>2.8.1</b> Importing data from an exported Qualtrics .csv file</a></li>
</ul></li>
<li class="chapter" data-level="2.9" data-path="scrub.html"><a href="scrub.html#references"><i class="fa fa-check"></i><b>2.9</b> References</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="score.html"><a href="score.html"><i class="fa fa-check"></i><b>3</b> Scoring</a>
<ul>
<li class="chapter" data-level="3.1" data-path="score.html"><a href="score.html#navigating-this-lesson-1"><i class="fa fa-check"></i><b>3.1</b> Navigating this Lesson</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="score.html"><a href="score.html#learning-objectives-1"><i class="fa fa-check"></i><b>3.1.1</b> Learning Objectives</a></li>
<li class="chapter" data-level="3.1.2" data-path="score.html"><a href="score.html#planning-for-practice-1"><i class="fa fa-check"></i><b>3.1.2</b> Planning for Practice</a></li>
<li class="chapter" data-level="3.1.3" data-path="score.html"><a href="score.html#readings-resources-1"><i class="fa fa-check"></i><b>3.1.3</b> Readings &amp; Resources</a></li>
<li class="chapter" data-level="3.1.4" data-path="score.html"><a href="score.html#packages-1"><i class="fa fa-check"></i><b>3.1.4</b> Packages</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="score.html"><a href="score.html#workflow-for-scrubbing-and-scoring-1"><i class="fa fa-check"></i><b>3.2</b> Workflow for Scrubbing and Scoring</a></li>
<li class="chapter" data-level="3.3" data-path="score.html"><a href="score.html#research-vignette-1"><i class="fa fa-check"></i><b>3.3</b> Research Vignette</a></li>
<li class="chapter" data-level="3.4" data-path="score.html"><a href="score.html#on-missing-data"><i class="fa fa-check"></i><b>3.4</b> On Missing Data</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="score.html"><a href="score.html#data-loss-mechanisms"><i class="fa fa-check"></i><b>3.4.1</b> Data Loss Mechanisms</a></li>
<li class="chapter" data-level="3.4.2" data-path="score.html"><a href="score.html#diagnosing-missing-data-mechanisms"><i class="fa fa-check"></i><b>3.4.2</b> Diagnosing Missing Data Mechanisms</a></li>
<li class="chapter" data-level="3.4.3" data-path="score.html"><a href="score.html#available-information-analysis"><i class="fa fa-check"></i><b>3.4.3</b> Available Information Analysis</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="score.html"><a href="score.html#working-the-problem-1"><i class="fa fa-check"></i><b>3.5</b> Working the Problem</a>
<ul>
<li class="chapter" data-level="3.5.1" data-path="score.html"><a href="score.html#missing-data-analysis-whole-df-and-item-level"><i class="fa fa-check"></i><b>3.5.1</b> Missing Data Analysis: Whole df and Item level</a></li>
<li class="chapter" data-level="3.5.2" data-path="score.html"><a href="score.html#analyzing-missing-data-patterns"><i class="fa fa-check"></i><b>3.5.2</b> Analyzing Missing Data Patterns</a></li>
<li class="chapter" data-level="3.5.3" data-path="score.html"><a href="score.html#missing-mechanisms"><i class="fa fa-check"></i><b>3.5.3</b> Missing Mechanisms</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="score.html"><a href="score.html#scoring"><i class="fa fa-check"></i><b>3.6</b> Scoring</a>
<ul>
<li class="chapter" data-level="3.6.1" data-path="score.html"><a href="score.html#reverse-scoring"><i class="fa fa-check"></i><b>3.6.1</b> Reverse scoring</a></li>
</ul></li>
<li class="chapter" data-level="3.7" data-path="score.html"><a href="score.html#missing-analysis-scale-level"><i class="fa fa-check"></i><b>3.7</b> Missing Analysis: Scale level</a></li>
<li class="chapter" data-level="3.8" data-path="score.html"><a href="score.html#revisiting-missing-analysis-at-the-scale-level"><i class="fa fa-check"></i><b>3.8</b> Revisiting Missing Analysis at the Scale Level</a>
<ul>
<li class="chapter" data-level="3.8.1" data-path="score.html"><a href="score.html#scale-level-patterns-of-missing-data"><i class="fa fa-check"></i><b>3.8.1</b> Scale Level: Patterns of Missing Data</a></li>
<li class="chapter" data-level="3.8.2" data-path="score.html"><a href="score.html#is-it-mcar"><i class="fa fa-check"></i><b>3.8.2</b> Is it MCAR?</a></li>
<li class="chapter" data-level="3.8.3" data-path="score.html"><a href="score.html#r-eady-for-analysis"><i class="fa fa-check"></i><b>3.8.3</b> R-eady for Analysis</a></li>
</ul></li>
<li class="chapter" data-level="3.9" data-path="score.html"><a href="score.html#the-apa-style-write-up"><i class="fa fa-check"></i><b>3.9</b> The APA Style Write-Up</a></li>
<li class="chapter" data-level="3.10" data-path="score.html"><a href="score.html#results"><i class="fa fa-check"></i><b>3.10</b> Results</a></li>
<li class="chapter" data-level="3.11" data-path="score.html"><a href="score.html#practice-problems-1"><i class="fa fa-check"></i><b>3.11</b> Practice Problems</a>
<ul>
<li class="chapter" data-level="3.11.1" data-path="score.html"><a href="score.html#problem-1-reworking-the-chapter-problem"><i class="fa fa-check"></i><b>3.11.1</b> Problem #1: Reworking the Chapter Problem</a></li>
<li class="chapter" data-level="3.11.2" data-path="score.html"><a href="score.html#problem-2-use-the-rate-a-recent-course-survey-choosing-different-variables-1"><i class="fa fa-check"></i><b>3.11.2</b> Problem #2: Use the <em>Rate-a-Recent-Course</em> Survey, Choosing Different Variables</a></li>
<li class="chapter" data-level="3.11.3" data-path="score.html"><a href="score.html#problem-3-other-data-1"><i class="fa fa-check"></i><b>3.11.3</b> Problem #3: Other data</a></li>
</ul></li>
<li class="chapter" data-level="3.12" data-path="score.html"><a href="score.html#bonus-reel"><i class="fa fa-check"></i><b>3.12</b> Bonus Reel:</a></li>
<li class="chapter" data-level="3.13" data-path="score.html"><a href="score.html#references-1"><i class="fa fa-check"></i><b>3.13</b> References</a></li>
</ul></li>
<li class="divider"></li>
#<li><a href="https:link" target="_blank">Open access book-in-progress</br>
<li><a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" /></a></li>
  <li><a href="https://bookdown.org" target="_blank">Built with Bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">DRAFT: ReCentering Psych Stats: Multivariate Modeling</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="score" class="section level1" number="3">
<h1><span class="header-section-number">Chapter 3</span> Scoring</h1>
<p>[Screencasted Lecture Link] <!-- TODO: Add link to screencast. --></p>
<p>The focus of this chapter is to continue the process of scrubbing-and-scoring. We continue with the raw data we downloaded and prepared in teh prior chapter. In this chapter we analyze and manage missingness, score scales/subscales, and represent our work with an APA-style write-up. To that end, we will address the conceptual considerations and practical steps in this process.</p>
<div id="navigating-this-lesson-1" class="section level2" number="3.1">
<h2><span class="header-section-number">3.1</span> Navigating this Lesson</h2>
<!-- TODO: Update how long it will take. -->
<p>There is about # hours and ## minutes of lecture. If you work through the materials with me it would be good to add another ## hours.</p>
<div id="learning-objectives-1" class="section level3" number="3.1.1">
<h3><span class="header-section-number">3.1.1</span> Learning Objectives</h3>
<p>Learning objectives from this lecture include the following:</p>
<ul>
<li>Recognize the key components of data loss mechanisms (MCAR, MAR, MNAR), including how to diagnose MCAR.</li>
<li>Interpret missingness figures produced by packages such as <em>mice</em> and <em>Amelia</em>.</li>
<li>Articulate a workflow for scrubbing and scoring data.</li>
<li>Use critical data manipulation functions from <em>dplyr</em> including <em>filter()</em>, <em>select()</em>, and <em>mutate()</em> to prepare variables.</li>
<li>Interpret code related to missingness (i.e., “is.na,” “!is.na”) and the pipe (%&gt;%)</li>
</ul>
</div>
<div id="planning-for-practice-1" class="section level3" number="3.1.2">
<h3><span class="header-section-number">3.1.2</span> Planning for Practice</h3>
<!-- TODO: Specify set of items to score for homework. -->
<p>Using Parent’s <span class="citation">(<a href="score.html#ref-parent_handling_2013" role="doc-biblioref">2013</a>)</span> AIA approach to managing missing data, “scrub and score” a raw dataset. Options of graded complexity could incude:</p>
<ul>
<li>Repeating the steps in the chapter; differences will be in the number of people who have completed the survey since the chapter was written.</li>
<li>Use the dataset that is the source of the chapter, but score a DIFFERENT SET OF ITEMS – MUST SPECIFY.</li>
<li>Begin with raw data to which you have access.</li>
</ul>
</div>
<div id="readings-resources-1" class="section level3" number="3.1.3">
<h3><span class="header-section-number">3.1.3</span> Readings &amp; Resources</h3>
<p>In preparing this chapter, I drew heavily from the following resource(s). Other resources are cited (when possible, linked) in the text with complete citations in the reference list.</p>
<ul>
<li><p>Parent, M. C. (2013). Handling item-level missing data: Simpler is just as good. The Counseling Psychologist, 41(4), 568–600. <a href="https://doi.org/10.1177/0011000012445176" class="uri">https://doi.org/10.1177/0011000012445176</a></p></li>
<li><p>Kline, R. B. (2015). Data preparation and psychometrics review. In Principles and Practice of Structural Equation Modeling, Fourth Edition. Guilford Publications. <a href="http://ebookcentral.proquest.com/lib/spu/detail.action?docID=4000663" class="uri">http://ebookcentral.proquest.com/lib/spu/detail.action?docID=4000663</a></p></li>
<li><p>Grolemund, G., &amp; Wickham, H. (n.d.). 5 Data transformation | R for Data Science. Retrieved March 12, 2020, from <a href="https://r4ds.had.co.nz/" class="uri">https://r4ds.had.co.nz/</a></p></li>
<li><p>Grolemund, G., &amp; Wickham, H. (n.d.). 3 Data visualization | R for Data Science. Retrieved March 12, 2020, from <a href="https://r4ds.had.co.nz/" class="uri">https://r4ds.had.co.nz/</a></p></li>
</ul>
</div>
<div id="packages-1" class="section level3" number="3.1.4">
<h3><span class="header-section-number">3.1.4</span> Packages</h3>
<p>The script below will (a) check to see if the following packages are installed on your computer and, if not (b) install them.</p>
<!-- TODO: Build out this section. -->
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="score.html#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span><span class="fu">require</span>(tidyverse)){<span class="fu">install.packages</span>(<span class="st">&quot;tidyverse&quot;</span>)}</span>
<span id="cb26-2"><a href="score.html#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span><span class="fu">require</span>(psych)){<span class="fu">install.packages</span>(<span class="st">&quot;psych&quot;</span>)}</span>
<span id="cb26-3"><a href="score.html#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span><span class="fu">require</span>(formattable)){<span class="fu">install.packages</span>(<span class="st">&quot;formattable&quot;</span>)}</span>
<span id="cb26-4"><a href="score.html#cb26-4" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span><span class="fu">require</span>(mice)){<span class="fu">install.packages</span>(<span class="st">&quot;mice&quot;</span>)}</span>
<span id="cb26-5"><a href="score.html#cb26-5" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span><span class="fu">require</span>(sjstats)){<span class="fu">install.packages</span>(<span class="st">&quot;sjstats&quot;</span>)}</span></code></pre></div>
</div>
</div>
<div id="workflow-for-scrubbing-and-scoring-1" class="section level2" number="3.2">
<h2><span class="header-section-number">3.2</span> Workflow for Scrubbing and Scoring</h2>
<p>The following is a proposed workflow for preparing data for analysis.</p>
<!-- TODO: When finalized, save as PDF so it can open in its own window) -->
<p>The same workflow guides us through the Scrubbing, Scoring, and Data dx chapters. At this stage we are at preliminary data diagnosis.</p>
<div class="figure">
<img src="images/Ch02/wrkflow_prelim.jpg" alt="" />
<p class="caption">An image of our stage in the workflow for scrubbing and scoring data.</p>
</div>
</div>
<div id="research-vignette-1" class="section level2" number="3.3">
<h2><span class="header-section-number">3.3</span> Research Vignette</h2>
<p>The research vignette comes from the survey titled, <a href="https://spupsych.az1.qualtrics.com/jfe/form/SV_b2cClqAlLGQ6nLU">Rate-a-Recent-Course: A ReCentering Psych Stats Exercise</a> and is explained in the prior chapter. In the prior chapter we conducted super-preliminary scrubbing of variables that will allow us to examine the the respondent’s perceived campus climate for students who are Black, predicted by the the respondent’s own campus belonging, and also the <em>structural diversity</em> proportions of Black students in the classroom and the BIPOC instructional staff. At present, I see this as a parallel mediation. That is, the perceived campus climate for Black students will be predicted by the respondent’s sense of belonging, through the proportion of Black classmates and BIPOC (Black, Indigenous, and people of color)instructional staff.</p>
<p><em>I would like to assess the model by having the instructional staff variable to be the %Black instructional staff. At the time that this lecture is being prepared, there is not sufficient Black representation in the staff to model this.</em></p>
<div class="figure">
<img src="images/Ch03/BlStuMod.jpg" alt="" />
<p class="caption">An image of the statistical model for which we are preparing data.</p>
</div>
<p>First, though, let’s take a more conceptual look at issues regarding missing data. We’ll come back to details of the survey as we work with it.</p>
</div>
<div id="on-missing-data" class="section level2" number="3.4">
<h2><span class="header-section-number">3.4</span> On Missing Data</h2>
<p>On the topic of missing data, we follow the traditions in most textbooks. We start by considering <em>data loss mechanisms</em> and options for <em>managing missingness.</em></p>
<p>Although the workflow I recommend is fairly straightforward, the topic is not. Quantitative psychologist have produced volumes of research that supports and refutes all of these issues in detail. An in-deth review of this is found in Enders’ <span class="citation">(<a href="score.html#ref-enders_applied_2010" role="doc-biblioref">Enders, 2010</a>)</span> text.</p>
<div id="data-loss-mechanisms" class="section level3" number="3.4.1">
<h3><span class="header-section-number">3.4.1</span> Data Loss Mechanisms</h3>
<p>We generally classify missingess in data in three different ways <span class="citation">(<a href="score.html#ref-kline_principles_2016" role="doc-biblioref">Kline, 2016</a>; <a href="score.html#ref-parent_handling_2013" role="doc-biblioref">Parent, 2013</a>)</span>:</p>
<p><strong>Missing completely at random (MCAR)</strong> is the ideal case (and often unrealistic in actual data). For variable <em>Y</em> this mean that</p>
<ul>
<li>Missingness is due to a factor(s) completely unrelated to the missing data. Stated another way:
<ul>
<li>Missing observations differ from the observed scores only by chance; that is, whether scores on Y are missing or not missing is unrelated to <em>Y</em> itself</li>
</ul></li>
<li>The presence versus absence of data on <em>Y</em> is unrelated to all other variables in the dataset. That is, the nonmissing data are just a random sample of scores that the researcher would have analyzed had the data been complete. We might think of it as <em>haphazard</em> missing.
<ul>
<li>A respondent is interrupted, looks up, looks down, and skips an item.</li>
<li>A computer glitch causes spotty missingness – unrelated to any particular variable.</li>
</ul></li>
</ul>
<p>MCAR is the ideal state because results from it should not be biased as a function of the missingness.</p>
<p><strong>Missing at random (MAR)</strong> missing data arise from a process that is both measured and predictable in a particular sample. <em>Admittedly the use of “random” in this term is odd, because, by definition, the missingness is not random.</em></p>
<p>Restated:</p>
<ol style="list-style-type: decimal">
<li>Missingness on Y is unrelated to Y itself, but</li>
<li>Missingness is on Y is correlated with other variables in the data set.</li>
</ol>
<p>Example: Men are less likely to respond to questions about mental health than women, but among men, the probability of responding is unrelated to their true mental health status.</p>
<p>Kline <span class="citation">(<a href="score.html#ref-kline_principles_2016" role="doc-biblioref">2016</a>)</span> indicated that information loss due to MAR is potentially recoverable through imputation where missing scores are replaced by predicted scores. The predicted scores are generated from other variables in the data set that predict missingness on Y. If the strength of that prediction is reasonably strong, then results on Y after imputation may be relatively unbiased. In this sense, the MAR pattern is described as <em>ignorable</em> with regard to potential bias. Two types of variables can be used to predict the missing data</p>
<ol style="list-style-type: decimal">
<li>variables that are in the prediction equation, and</li>
<li><em>auxiliary</em> variables (i.e., variables in the dataset that are not in the prediction equation).</li>
</ol>
<p>Parent <span class="citation">(<a href="score.html#ref-parent_handling_2013" role="doc-biblioref">2013</a>)</span> noted that multiple imputation and expectation maximization have frequently been used to manage missingness in MAR circumstances.</p>
<p><strong>Missing not at random (MNAR)</strong> is when the presence versus absence of scores on <em>Y</em> depend on <em>Y</em> itself. This is <em>non-ignorable</em>.</p>
<p>For example, if a patient drops out of a medical RCT because there are unpleasant side effects from the treatment, this discomfort is not measured, but the data is missing due to a process that is unknown in a particular data set. Results based on <em>complete cases only</em> can be severely biased when the data loss pattern is MNAR. That is, a treatment may look more beneficial than it really is if data from patients who were unable to tolerate the treatment are lost.</p>
<p>Parent <span class="citation">(<a href="score.html#ref-parent_handling_2013" role="doc-biblioref">2013</a>)</span> described MNAR a little differently – but emphasized that the systematic missingness would be related to a variable outside the datset. Parent provided the example of items written in a manner that may be inappropriate for some participants (e.g., asking women about a relationship with their boyfriend/husband, when the woman might be in same gender relationship). If there were not demographic items that could identify the bias, this would be MNAR. Parent strongly advises researchers to carefully proofread and pilot surveys to avoid MNAR circumstances.</p>
<p>Kline <span class="citation">(<a href="score.html#ref-kline_principles_2016" role="doc-biblioref">2016</a>)</span> noted that the choice of the method to deal with the incomplete records can make a difference in the results, and should be made carefully.</p>
</div>
<div id="diagnosing-missing-data-mechanisms" class="section level3" number="3.4.2">
<h3><span class="header-section-number">3.4.2</span> Diagnosing Missing Data Mechanisms</h3>
<p>The bad news is that we never really know (with certainty) the type of missing data mechanism in our data. The following tools can help understand the mechanisms that contribute to missingness.</p>
<ul>
<li>Missing data analyses often includes correlations that could predict missingness.</li>
<li>Little and Rubin <span class="citation">(<a href="score.html#ref-little_statistical_2002" role="doc-biblioref">Little &amp; Rubin, 2002</a>)</span> proposed a multivariate statistical test of the MCAR assumption that simultaneously compares complete versus incomplete cases on <em>Y</em> across all other variables. If this comparison is significant, then the MCAR hypothesis is rejected.
<ul>
<li>To restate: we want a non-significant result; and we use the sometimes-backwards-sounding NHST (null hypothesis significance testing) language, “MCAR cannot be rejected.”</li>
</ul></li>
<li>MCAR can also be examined through a series of <em>t</em> tests of the cases that have missing scores on Y with cases that have complete records on other variables. Unfortunately, sample sizes contribute to problems with interpretation. With low samples, they are underpowered; in large samples they can flag trivial differences.</li>
</ul>
<p>If MCAR is rejected, we are never sure whether the data loss mechanism is MAR or MNAR. There is no magical statistical “fix.” Kline <span class="citation">(<a href="score.html#ref-kline_principles_2016" role="doc-biblioref">2016</a>)</span> wrote, “About the best that can be done is to understand the nature of the underlying data loss pattern and accordingly modify your interpretation of the results” (p. 85).</p>
</div>
<div id="available-information-analysis" class="section level3" number="3.4.3">
<h3><span class="header-section-number">3.4.3</span> Available Information Analysis</h3>
<p>Parent <span class="citation">(<a href="score.html#ref-parent_handling_2013" role="doc-biblioref">2013</a>)</span> has created a set of recommendations that help us create a streamlined workflow for managing missing data. Parent concluded that in datasets with (a) low levels of missingness, (b) a reasonable sample size, and (c) adequate internal reliability of measures, that <em>available information anlaysis</em> (AIA), mean substitution, and multiple imputation had similar results.</p>
<p>Further, in simulation studies where there was (a) low sample size (<em>n</em> = 50), (b) weak associations among items, and (c) a small number of missing items, AIA was equivalent to multiple imputation. Even in cases where the data conditions were the “best” (i.e., <em>N</em> = 200, moderate correlations, at least 10 items), even 10% missingness (overall) did not produce notable difference among the methods. That is, means, standard errors, and alphas were similar across the methods (AIA, mean substitution, multiple imputation).</p>
<p>AIA is an older method of handling missing data that, as its name suggests, uses the <em>available data</em> for analysis and excludes missing data points only for analyses in which the missing data point would be directly involved. This means</p>
<ul>
<li>In the case of research that uses multiple item scales, and analysis takes place at the scale level
<ul>
<li>AIA is used to generate <strong>mean</strong> scores for the scale using the available data without substituting or imputing values;</li>
<li>This method generally produces a fairly complete set of scale-level data where
<ul>
<li>pairwise deletion (the whole row/case/person is skipped) can be used for many analyses that do not permit missing data: correlations, t-tests, ANOVA</li>
<li>FIML can be specified in path analysis (if scale scores are missing) and CFA/SEM (where item-level data is required), and</li>
<li>some statistics, such as principal components analysis (an item-level analysis) permit missing data,</li>
</ul></li>
<li>Of course, the researcher could still impute data, but why…</li>
</ul></li>
</ul>
<p>Parent’s<span class="citation">(<a href="score.html#ref-parent_handling_2013" role="doc-biblioref">2013</a>)</span> recommendations:</p>
<ul>
<li>Scale scores should be first calculated as a <em>mean</em> (average) not a sum. Why?
<ul>
<li>Calculating a “sum” from available data will result in automatically lower scores in cases where there is missingness.</li>
<li>If a sum is required (i.e., because you want to interpret some clinical level of something), calculate the mean first, do the analyse, then transform the results back into the whole-scale equivalent (multiply the mean by the number of items) for any interpretation (or do some math around the sum-level interpretation so that you can interpret a mean).</li>
<li>For R script, do not write the script ([item1 + item2 + item3]/3) because this will return an empty entry for participants missing data (same problem as if you were to use sum). There are several functions for properly computing a mean; I will demo the <em>mean_n()</em> function from <em>sjstats</em> package because it allows us to simultaneously specify the tolerance level (next item).</li>
</ul></li>
<li>Determine your <em>tolerance</em> for missingness (20% seems to be common, although you could also look for guidance in the test manual/article). Then
<ul>
<li>Run a “percent missingness” check on the level of analysis (i.e., total score, scale, or subscale) you are using. If you are using a total scale score, then check to see what percent is missing across all the items in the whole scale. In contrast, if you are looking at subscales, run the percent missing at that level.</li>
<li>Parent <span class="citation">(<a href="score.html#ref-parent_handling_2013" role="doc-biblioref">2013</a>)</span> advised that the tolerance levels should be made mindfully. A four-item scale with one item missing, won’t meet the 80% threshold, so it may make sense to set a 75% threshold for this scale.</li>
</ul></li>
<li>“Clearly and concisely detail the level of missingness” in papers <span class="citation">(<a href="score.html#ref-parent_handling_2013" role="doc-biblioref">Parent, 2013, p. 595</a>)</span>. This includes
<ul>
<li>tolerance level for missing data by scale or subscale (e.g., 80% or 75%)</li>
<li>the number of missing values out of all data points on that scale for all participants and the maximum by participant (e.g., “For Scale X, a total of # missing data points out of ### were observed with no participant missing more than a single point.”)</li>
<li>verify a manual inspection of missing data for obvious patterns (e.g., abnormally high missing rates for only one or two items). This can be accomplished by requesting frequency output for the items and checking the nonmissing data points for each scale, ensuring there are no abnormal spikes in missingness (looking for MNAR).</li>
</ul></li>
<li>Curiously, Parent <span class="citation">(<a href="score.html#ref-parent_handling_2013" role="doc-biblioref">2013</a>)</span> does not recommend that we run all the diagnostic tests. However, because recent reviewers have required them of me, I will demonstrate a series of them, including MCAR.</li>
<li>Reducing missingness starts at the survey design – make sure that all people can answer all items (i.e,. relationship-related items may contain heterosexist assumptions…which would result in an MNAR circumstance)</li>
</ul>
<p>Very practically speaking, Parent’s <span class="citation">(<a href="score.html#ref-parent_handling_2013" role="doc-biblioref">2013</a>)</span> recommendations follow us through the entire data analysis process.</p>
<ul>
<li>We will use a tolerance of 20%.
<ul>
<li>We will create 2 variables (n_miss and prop_miss) for each of the scales, these will be used two ways.</li>
<li>In combination, we will delete individuals who have 100% missing data on these 3 scores (this was an individual decision for this particular dataset; it could be different depending on your analytic approach)</li>
<li>We will calculate scale scores only on those with 80% of data present.</li>
</ul></li>
<li>After calculating the scale scores, we will return to analyzing the missingness, looking at the whole dataset.</li>
</ul>
</div>
</div>
<div id="working-the-problem-1" class="section level2" number="3.5">
<h2><span class="header-section-number">3.5</span> Working the Problem</h2>
<p>In the prior chapter we imported the data from Qualtrics and applied the broadest levels of inclusion (e.g., the course rated was offered from an institution in the U.S., the respondent consented to participation) and exclusion (e.g., the survey was not a preview). We then downsized the survey to include the variables we will use in our statistical model. We then saved the data in a .csv file.</p>
<p>Presuming that you are working along with me in an .rmd file, if you have placed that file in the same folder as this .rmd file, the following code should read the data into your environment.</p>
<p>I use <em>different</em> names for the object/df in my R environment than I use for the filename that holds the data on my computer. Why? I don’t want to accidentally overwrite this precious “source” of data.</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="score.html#cb27-1" aria-hidden="true" tabindex="-1"></a>scrub_df <span class="ot">&lt;-</span> <span class="fu">read.csv</span> (<span class="st">&quot;BlackStntsModel210318.csv&quot;</span>, <span class="at">head =</span> <span class="cn">TRUE</span>, <span class="at">sep =</span> <span class="st">&quot;,&quot;</span>)</span>
<span id="cb27-2"><a href="score.html#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(scrub_df)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    29 obs. of  25 variables:
##  $ ID       : int  1 2 3 4 5 6 7 8 9 10 ...
##  $ iRace1   : int  3 3 3 3 1 3 3 3 1 0 ...
##  $ iRace2   : int  1 NA 1 1 NA NA 3 NA NA 0 ...
##  $ iRace3   : int  3 NA NA 3 NA NA NA NA NA 3 ...
##  $ iRace4   : int  NA NA NA NA NA NA NA NA NA 3 ...
##  $ iRace5   : logi  NA NA NA NA NA NA ...
##  $ iRace6   : logi  NA NA NA NA NA NA ...
##  $ iRace7   : logi  NA NA NA NA NA NA ...
##  $ iRace8   : logi  NA NA NA NA NA NA ...
##  $ iRace9   : logi  NA NA NA NA NA NA ...
##  $ iRace10  : logi  NA NA NA NA NA NA ...
##  $ cmBiMulti: int  0 0 0 2 5 15 0 0 0 7 ...
##  $ cmBlack  : int  0 5 10 6 5 20 0 0 0 4 ...
##  $ cmNBPoC  : int  39 10 30 19 10 30 40 5 30 13 ...
##  $ cmWhite  : int  61 85 60 73 80 35 60 90 70 73 ...
##  $ cmUnsure : int  0 0 0 0 0 0 0 5 0 3 ...
##  $ Belong_1 : int  6 4 NA 5 4 5 6 7 6 3 ...
##  $ Belong_2 : int  6 4 3 3 4 6 6 7 6 3 ...
##  $ Belong_3 : int  7 6 NA 2 4 5 5 7 6 3 ...
##  $ Blst_1   : int  5 6 NA 2 6 5 5 5 5 3 ...
##  $ Blst_2   : int  3 6 5 2 1 1 4 4 3 5 ...
##  $ Blst_3   : int  5 2 2 2 1 1 4 3 1 2 ...
##  $ Blst_4   : int  2 2 2 2 1 2 4 3 2 3 ...
##  $ Blst_5   : int  2 4 NA 2 1 1 4 4 1 3 ...
##  $ Blst_6   : int  2 1 2 2 1 2 4 3 2 3 ...</code></pre>
<p>Let’s think about how the variables in our model should be measured:</p>
<ul>
<li>DV: Campus Climate for Black Students (as perceived by the respondent)
<ul>
<li>mean score of the 6 items on that scale (higher scores indicate a climate characterized by hostility, nonresponsiveness, and stigma)</li>
<li>1 item needs to be reverse-coded</li>
<li>this scale was adapted from the LGBT Campus Climate Scale <span class="citation">(<a href="score.html#ref-szymanski_perceptions_2020" role="doc-biblioref">Szymanski &amp; Bissonette, 2020</a>)</span></li>
</ul></li>
<li>IV: Belonging
<ul>
<li>mean score for the 3 items on that scale (higher scores indicate a greater sense of belonging)</li>
<li>this scale is taken from the Sense of Belonging subscale from the Perceived Cohesion Scale <span class="citation">(<a href="score.html#ref-bollen_perceived_1990" role="doc-biblioref">Bollen &amp; Hoyle, 1990</a>)</span></li>
</ul></li>
<li>Proportion of classmates who are Black
<ul>
<li>a single item</li>
</ul></li>
<li>Proportion of instructional staff who are BIPOC
<ul>
<li>must be calculated from each of the single items for each instructor</li>
</ul></li>
</ul>
<p>Our next step is to conduct a preliminary missing data analysis at the item level, across the dataset we are using. The Campus Climate and Belonging scales are traditional in the sense that they have items that we sum. The variable representing proportion of classmates who are Black is a single item. The variable representing the proportion of instructional staff who are BIPOC must be calculated in a manner that takes into consideration the there may be multiple instructors. The survey allowed a respondent to name up to 10 instructors.</p>
<p>Looking at the structure of our data, the iRace(1 thru 10) variables are in “int” or integer format. This means that they are represented as whole numbers. We need them to be represented as factors. R handles factors represented as words well. Therefore, let’s use our codebook to reformat this variable, first from integer to factor and second represented with words instead of numbers.</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="score.html#cb29-1" aria-hidden="true" tabindex="-1"></a>scrub_df[,<span class="st">&#39;iRace1&#39;</span>] <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(scrub_df[,<span class="st">&#39;iRace1&#39;</span>])</span>
<span id="cb29-2"><a href="score.html#cb29-2" aria-hidden="true" tabindex="-1"></a>scrub_df[,<span class="st">&#39;iRace2&#39;</span>] <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(scrub_df[,<span class="st">&#39;iRace2&#39;</span>])</span>
<span id="cb29-3"><a href="score.html#cb29-3" aria-hidden="true" tabindex="-1"></a>scrub_df[,<span class="st">&#39;iRace3&#39;</span>] <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(scrub_df[,<span class="st">&#39;iRace3&#39;</span>])</span>
<span id="cb29-4"><a href="score.html#cb29-4" aria-hidden="true" tabindex="-1"></a>scrub_df[,<span class="st">&#39;iRace4&#39;</span>] <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(scrub_df[,<span class="st">&#39;iRace4&#39;</span>])</span>
<span id="cb29-5"><a href="score.html#cb29-5" aria-hidden="true" tabindex="-1"></a>scrub_df[,<span class="st">&#39;iRace5&#39;</span>] <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(scrub_df[,<span class="st">&#39;iRace5&#39;</span>])</span>
<span id="cb29-6"><a href="score.html#cb29-6" aria-hidden="true" tabindex="-1"></a>scrub_df[,<span class="st">&#39;iRace6&#39;</span>] <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(scrub_df[,<span class="st">&#39;iRace6&#39;</span>])</span>
<span id="cb29-7"><a href="score.html#cb29-7" aria-hidden="true" tabindex="-1"></a>scrub_df[,<span class="st">&#39;iRace7&#39;</span>] <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(scrub_df[,<span class="st">&#39;iRace7&#39;</span>])</span>
<span id="cb29-8"><a href="score.html#cb29-8" aria-hidden="true" tabindex="-1"></a>scrub_df[,<span class="st">&#39;iRace8&#39;</span>] <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(scrub_df[,<span class="st">&#39;iRace8&#39;</span>])</span>
<span id="cb29-9"><a href="score.html#cb29-9" aria-hidden="true" tabindex="-1"></a>scrub_df[,<span class="st">&#39;iRace9&#39;</span>] <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(scrub_df[,<span class="st">&#39;iRace9&#39;</span>])</span>
<span id="cb29-10"><a href="score.html#cb29-10" aria-hidden="true" tabindex="-1"></a>scrub_df[,<span class="st">&#39;iRace10&#39;</span>] <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(scrub_df[,<span class="st">&#39;iRace10&#39;</span>])</span></code></pre></div>
<p>Let’s check the structure to see if they are factors.</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="score.html#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(scrub_df)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    29 obs. of  25 variables:
##  $ ID       : int  1 2 3 4 5 6 7 8 9 10 ...
##  $ iRace1   : Factor w/ 4 levels &quot;0&quot;,&quot;1&quot;,&quot;2&quot;,&quot;3&quot;: 4 4 4 4 2 4 4 4 2 1 ...
##  $ iRace2   : Factor w/ 3 levels &quot;0&quot;,&quot;1&quot;,&quot;3&quot;: 2 NA 2 2 NA NA 3 NA NA 1 ...
##  $ iRace3   : Factor w/ 2 levels &quot;1&quot;,&quot;3&quot;: 2 NA NA 2 NA NA NA NA NA 2 ...
##  $ iRace4   : Factor w/ 2 levels &quot;2&quot;,&quot;3&quot;: NA NA NA NA NA NA NA NA NA 2 ...
##  $ iRace5   : Factor w/ 0 levels: NA NA NA NA NA NA NA NA NA NA ...
##  $ iRace6   : Factor w/ 0 levels: NA NA NA NA NA NA NA NA NA NA ...
##  $ iRace7   : Factor w/ 0 levels: NA NA NA NA NA NA NA NA NA NA ...
##  $ iRace8   : Factor w/ 0 levels: NA NA NA NA NA NA NA NA NA NA ...
##  $ iRace9   : Factor w/ 0 levels: NA NA NA NA NA NA NA NA NA NA ...
##  $ iRace10  : Factor w/ 0 levels: NA NA NA NA NA NA NA NA NA NA ...
##  $ cmBiMulti: int  0 0 0 2 5 15 0 0 0 7 ...
##  $ cmBlack  : int  0 5 10 6 5 20 0 0 0 4 ...
##  $ cmNBPoC  : int  39 10 30 19 10 30 40 5 30 13 ...
##  $ cmWhite  : int  61 85 60 73 80 35 60 90 70 73 ...
##  $ cmUnsure : int  0 0 0 0 0 0 0 5 0 3 ...
##  $ Belong_1 : int  6 4 NA 5 4 5 6 7 6 3 ...
##  $ Belong_2 : int  6 4 3 3 4 6 6 7 6 3 ...
##  $ Belong_3 : int  7 6 NA 2 4 5 5 7 6 3 ...
##  $ Blst_1   : int  5 6 NA 2 6 5 5 5 5 3 ...
##  $ Blst_2   : int  3 6 5 2 1 1 4 4 3 5 ...
##  $ Blst_3   : int  5 2 2 2 1 1 4 3 1 2 ...
##  $ Blst_4   : int  2 2 2 2 1 2 4 3 2 3 ...
##  $ Blst_5   : int  2 4 NA 2 1 1 4 4 1 3 ...
##  $ Blst_6   : int  2 1 2 2 1 2 4 3 2 3 ...</code></pre>
<p>They are now factors. Let’s recode their representation as integers into representation as labels. We could totally recode each into itself, but I want to visually inspect to make sure it recodes correctly. Earlier I used “i” to indicate “instructor”; I will simply changet that to “t” (teacher).</p>
<p>The mutate code below is from dplyr – a member of the tidyverse family. The use of the pipe (%&gt;%) allows us to string together a number of commands into a single operation. I’m sure there are ways to do this with concatonated lists, but with copy and paste this was simple enough.</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="score.html#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb32-2"><a href="score.html#cb32-2" aria-hidden="true" tabindex="-1"></a>scrub_df <span class="ot">&lt;-</span> scrub_df <span class="sc">%&gt;%</span></span>
<span id="cb32-3"><a href="score.html#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">tRace1 =</span> <span class="fu">recode</span>(iRace1, <span class="st">&quot;0&quot;</span> <span class="ot">=</span> <span class="st">&quot;Black&quot;</span>, <span class="st">&quot;1&quot;</span> <span class="ot">=</span> <span class="st">&quot;nBpoc&quot;</span>, <span class="st">&quot;2&quot;</span> <span class="ot">=</span> <span class="st">&quot;BiMulti&quot;</span>, <span class="st">&quot;3&quot;</span> <span class="ot">=</span> <span class="st">&quot;White&quot;</span>, <span class="st">&quot;4&quot;</span> <span class="ot">=</span> <span class="st">&quot;NotNotice&quot;</span>))<span class="sc">%&gt;%</span></span>
<span id="cb32-4"><a href="score.html#cb32-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">tRace2 =</span> <span class="fu">recode</span>(iRace2, <span class="st">&quot;0&quot;</span> <span class="ot">=</span> <span class="st">&quot;Black&quot;</span>, <span class="st">&quot;1&quot;</span> <span class="ot">=</span> <span class="st">&quot;nBpoc&quot;</span>, <span class="st">&quot;2&quot;</span> <span class="ot">=</span> <span class="st">&quot;BiMulti&quot;</span>, <span class="st">&quot;3&quot;</span> <span class="ot">=</span> <span class="st">&quot;White&quot;</span>, <span class="st">&quot;4&quot;</span> <span class="ot">=</span> <span class="st">&quot;NotNotice&quot;</span>))<span class="sc">%&gt;%</span></span>
<span id="cb32-5"><a href="score.html#cb32-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">tRace3 =</span> <span class="fu">recode</span>(iRace3, <span class="st">&quot;0&quot;</span> <span class="ot">=</span> <span class="st">&quot;Black&quot;</span>, <span class="st">&quot;1&quot;</span> <span class="ot">=</span> <span class="st">&quot;nBpoc&quot;</span>, <span class="st">&quot;2&quot;</span> <span class="ot">=</span> <span class="st">&quot;BiMulti&quot;</span>, <span class="st">&quot;3&quot;</span> <span class="ot">=</span> <span class="st">&quot;White&quot;</span>, <span class="st">&quot;4&quot;</span> <span class="ot">=</span> <span class="st">&quot;NotNotice&quot;</span>))<span class="sc">%&gt;%</span></span>
<span id="cb32-6"><a href="score.html#cb32-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">tRace4 =</span> <span class="fu">recode</span>(iRace4, <span class="st">&quot;0&quot;</span> <span class="ot">=</span> <span class="st">&quot;Black&quot;</span>, <span class="st">&quot;1&quot;</span> <span class="ot">=</span> <span class="st">&quot;nBpoc&quot;</span>, <span class="st">&quot;2&quot;</span> <span class="ot">=</span> <span class="st">&quot;BiMulti&quot;</span>, <span class="st">&quot;3&quot;</span> <span class="ot">=</span> <span class="st">&quot;White&quot;</span>, <span class="st">&quot;4&quot;</span> <span class="ot">=</span> <span class="st">&quot;NotNotice&quot;</span>))<span class="sc">%&gt;%</span></span>
<span id="cb32-7"><a href="score.html#cb32-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">tRace5 =</span> <span class="fu">recode</span>(iRace5, <span class="st">&quot;0&quot;</span> <span class="ot">=</span> <span class="st">&quot;Black&quot;</span>, <span class="st">&quot;1&quot;</span> <span class="ot">=</span> <span class="st">&quot;nBpoc&quot;</span>, <span class="st">&quot;2&quot;</span> <span class="ot">=</span> <span class="st">&quot;BiMulti&quot;</span>, <span class="st">&quot;3&quot;</span> <span class="ot">=</span> <span class="st">&quot;White&quot;</span>, <span class="st">&quot;4&quot;</span> <span class="ot">=</span> <span class="st">&quot;NotNotice&quot;</span>))<span class="sc">%&gt;%</span></span>
<span id="cb32-8"><a href="score.html#cb32-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">tRace6 =</span> <span class="fu">recode</span>(iRace6, <span class="st">&quot;0&quot;</span> <span class="ot">=</span> <span class="st">&quot;Black&quot;</span>, <span class="st">&quot;1&quot;</span> <span class="ot">=</span> <span class="st">&quot;nBpoc&quot;</span>, <span class="st">&quot;2&quot;</span> <span class="ot">=</span> <span class="st">&quot;BiMulti&quot;</span>, <span class="st">&quot;3&quot;</span> <span class="ot">=</span> <span class="st">&quot;White&quot;</span>, <span class="st">&quot;4&quot;</span> <span class="ot">=</span> <span class="st">&quot;NotNotice&quot;</span>))<span class="sc">%&gt;%</span></span>
<span id="cb32-9"><a href="score.html#cb32-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">tRace7 =</span> <span class="fu">recode</span>(iRace7, <span class="st">&quot;0&quot;</span> <span class="ot">=</span> <span class="st">&quot;Black&quot;</span>, <span class="st">&quot;1&quot;</span> <span class="ot">=</span> <span class="st">&quot;nBpoc&quot;</span>, <span class="st">&quot;2&quot;</span> <span class="ot">=</span> <span class="st">&quot;BiMulti&quot;</span>, <span class="st">&quot;3&quot;</span> <span class="ot">=</span> <span class="st">&quot;White&quot;</span>, <span class="st">&quot;4&quot;</span> <span class="ot">=</span> <span class="st">&quot;NotNotice&quot;</span>))<span class="sc">%&gt;%</span></span>
<span id="cb32-10"><a href="score.html#cb32-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">tRace8 =</span> <span class="fu">recode</span>(iRace8, <span class="st">&quot;0&quot;</span> <span class="ot">=</span> <span class="st">&quot;Black&quot;</span>, <span class="st">&quot;1&quot;</span> <span class="ot">=</span> <span class="st">&quot;nBpoc&quot;</span>, <span class="st">&quot;2&quot;</span> <span class="ot">=</span> <span class="st">&quot;BiMulti&quot;</span>, <span class="st">&quot;3&quot;</span> <span class="ot">=</span> <span class="st">&quot;White&quot;</span>, <span class="st">&quot;4&quot;</span> <span class="ot">=</span> <span class="st">&quot;NotNotice&quot;</span>))<span class="sc">%&gt;%</span></span>
<span id="cb32-11"><a href="score.html#cb32-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">tRace9 =</span> <span class="fu">recode</span>(iRace9, <span class="st">&quot;0&quot;</span> <span class="ot">=</span> <span class="st">&quot;Black&quot;</span>, <span class="st">&quot;1&quot;</span> <span class="ot">=</span> <span class="st">&quot;nBpoc&quot;</span>, <span class="st">&quot;2&quot;</span> <span class="ot">=</span> <span class="st">&quot;BiMulti&quot;</span>, <span class="st">&quot;3&quot;</span> <span class="ot">=</span> <span class="st">&quot;White&quot;</span>, <span class="st">&quot;4&quot;</span> <span class="ot">=</span> <span class="st">&quot;NotNotice&quot;</span>))<span class="sc">%&gt;%</span></span>
<span id="cb32-12"><a href="score.html#cb32-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">tRace10 =</span> <span class="fu">recode</span>(iRace10, <span class="st">&quot;0&quot;</span> <span class="ot">=</span> <span class="st">&quot;Black&quot;</span>, <span class="st">&quot;1&quot;</span> <span class="ot">=</span> <span class="st">&quot;nBpoc&quot;</span>, <span class="st">&quot;2&quot;</span> <span class="ot">=</span> <span class="st">&quot;BiMulti&quot;</span>, <span class="st">&quot;3&quot;</span> <span class="ot">=</span> <span class="st">&quot;White&quot;</span>, <span class="st">&quot;4&quot;</span> <span class="ot">=</span> <span class="st">&quot;NotNotice&quot;</span>))</span></code></pre></div>
<p>Calculating the proportion of the not-White instructional staff could likely be accomplished a number of ways. My searching for solutions resulted in this. Hopefully it’s a fair balance between intuitive and elegant coding. First, I created code that</p>
<ul>
<li>created a new variable (count.BIPOC) by</li>
<li>summing across the tRace1 through tRace10 variables,</li>
<li>assigning a count of “1,”</li>
<li>each time the factor value was Black, nBpoc, or BiMulti</li>
</ul>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="score.html#cb33-1" aria-hidden="true" tabindex="-1"></a>scrub_df<span class="sc">$</span>count.BIPOC <span class="ot">&lt;-</span> <span class="fu">apply</span>(scrub_df[<span class="fu">c</span>(<span class="st">&quot;tRace1&quot;</span>, <span class="st">&quot;tRace2&quot;</span>, <span class="st">&quot;tRace3&quot;</span>, <span class="st">&quot;tRace4&quot;</span>, <span class="st">&quot;tRace5&quot;</span>, <span class="st">&quot;tRace6&quot;</span>, <span class="st">&quot;tRace7&quot;</span>, <span class="st">&quot;tRace8&quot;</span>, <span class="st">&quot;tRace9&quot;</span>, <span class="st">&quot;tRace10&quot;</span>)], <span class="dv">1</span>, <span class="cf">function</span>(x) <span class="fu">sum</span>(x <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">&quot;Black&quot;</span>, <span class="st">&quot;nBpoc&quot;</span>, <span class="st">&quot;BiMulti&quot;</span>)))</span></code></pre></div>
<p>Next, I created a variable that counted the number of non-missing values across the tRace1 through tRace10 variables.</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="score.html#cb34-1" aria-hidden="true" tabindex="-1"></a>scrub_df<span class="sc">$</span>count.nMiss <span class="ot">&lt;-</span> <span class="fu">apply</span>(scrub_df[<span class="fu">c</span>(<span class="st">&quot;tRace1&quot;</span>, <span class="st">&quot;tRace2&quot;</span>, <span class="st">&quot;tRace3&quot;</span>, <span class="st">&quot;tRace4&quot;</span>, <span class="st">&quot;tRace5&quot;</span>, <span class="st">&quot;tRace6&quot;</span>, <span class="st">&quot;tRace7&quot;</span>, <span class="st">&quot;tRace8&quot;</span>, <span class="st">&quot;tRace9&quot;</span>, <span class="st">&quot;tRace10&quot;</span>)], <span class="dv">1</span>, <span class="cf">function</span>(x) <span class="fu">sum</span>(<span class="sc">!</span><span class="fu">is.na</span>(x)))</span></code></pre></div>
<p>Now to calculate the proportion of BIPOC instructional faculty for each case.</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="score.html#cb35-1" aria-hidden="true" tabindex="-1"></a>scrub_df<span class="sc">$</span>iBIPOC_pr <span class="ot">=</span> scrub_df<span class="sc">$</span>count.BIPOC<span class="sc">/</span>scrub_df<span class="sc">$</span>count.nMiss</span></code></pre></div>
<div id="missing-data-analysis-whole-df-and-item-level" class="section level3" number="3.5.1">
<h3><span class="header-section-number">3.5.1</span> Missing Data Analysis: Whole df and Item level</h3>
<p>In understanding missingness across the dataset, I think it is important to analyze and manage it, iteratively. We will start with a view of the whole df-level missingness. Subsequently, and consistent with the available information analysis [AIA; <span class="citation"><a href="score.html#ref-parent_handling_2013" role="doc-biblioref">Parent</a> (<a href="score.html#ref-parent_handling_2013" role="doc-biblioref">2013</a>)</span>] approach, we will score the scales and then look again at missingness, using the new information to update our decisions about how to manage it.</p>
<div class="figure">
<img src="images/Ch02/wrkflow_item_lvl.jpg" alt="" />
<p class="caption">An image of our stage in the workflow for scrubbing and scoring data.</p>
</div>
<p>Because we just created a host of new variables in creating the <em>prop_BIPOC</em> variable, let’s downsize the df so that the calculations are sensible.</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="score.html#cb36-1" aria-hidden="true" tabindex="-1"></a>scrub_df <span class="ot">&lt;-</span>(<span class="fu">select</span> (scrub_df, ID, iBIPOC_pr, cmBlack, Belong_1<span class="sc">:</span>Belong_3, Blst_1<span class="sc">:</span>Blst_6))</span></code></pre></div>
<p>With a couple of calculations, we create a proportion of item-level missingness.</p>
<p>In this chunk I first calculate the number of missing (nmiss)</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="score.html#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Calculating number and proportion of item-level missingness</span></span>
<span id="cb37-2"><a href="score.html#cb37-2" aria-hidden="true" tabindex="-1"></a>scrub_df<span class="sc">$</span>nmiss <span class="ot">&lt;-</span> scrub_df<span class="sc">%&gt;%</span></span>
<span id="cb37-3"><a href="score.html#cb37-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(iBIPOC_pr<span class="sc">:</span>Blst_6) <span class="sc">%&gt;%</span> <span class="co">#the colon allows us to include all variables between the two listed (the variables need to be in order)</span></span>
<span id="cb37-4"><a href="score.html#cb37-4" aria-hidden="true" tabindex="-1"></a>    is.na <span class="sc">%&gt;%</span> </span>
<span id="cb37-5"><a href="score.html#cb37-5" aria-hidden="true" tabindex="-1"></a>    rowSums</span>
<span id="cb37-6"><a href="score.html#cb37-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-7"><a href="score.html#cb37-7" aria-hidden="true" tabindex="-1"></a>scrub_df<span class="ot">&lt;-</span> scrub_df<span class="sc">%&gt;%</span></span>
<span id="cb37-8"><a href="score.html#cb37-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">prop_miss =</span> (nmiss<span class="sc">/</span><span class="dv">11</span>)<span class="sc">*</span><span class="dv">100</span>) <span class="co">#11 is the number of variables included in calculating the proportion</span></span></code></pre></div>
<p>We can grab the descriptives for the <em>prop_miss</em> variable to begin to understand our data. I will create an object from it so I can use it with inline</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="score.html#cb38-1" aria-hidden="true" tabindex="-1"></a>CaseMiss<span class="ot">&lt;-</span>psych<span class="sc">::</span><span class="fu">describe</span>(scrub_df<span class="sc">$</span>prop_miss)</span>
<span id="cb38-2"><a href="score.html#cb38-2" aria-hidden="true" tabindex="-1"></a>CaseMiss</span></code></pre></div>
<pre><code>##    vars  n mean    sd median trimmed mad min   max range skew kurtosis   se
## X1    1 29 4.39 10.48      0    2.18   0   0 36.36 36.36 2.27     3.78 1.95</code></pre>
<p>CUMULATIVE CAPTURE FOR WRITING IT UP: Across cases that were deemed eligible on the basis of the inclusion/exclusion criteria, missingness ranged from 0 to 36.3636364.</p>
<p>At the time that I am lecturing this, the the amount of missing is not so aggregious that I want to eliminate any cases. That is, I’m willing to wait until after I score the items to make further decisions, then.</p>
<p>Because (a) I want to teach it and (b) it is quite likely that we will receive responses with high levels of missingness, I will write code to eliminate cases with <span class="math inline">\(\geq\)</span> 90%.</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="score.html#cb40-1" aria-hidden="true" tabindex="-1"></a>scrub_df <span class="ot">&lt;-</span> <span class="fu">filter</span>(scrub_df, prop_miss <span class="sc">&lt;=</span> <span class="dv">90</span>)  <span class="co">#update df to have only those with at least 90% of complete data</span></span></code></pre></div>
<p>To analyze missingness at this level, we need a df that has only the variables of interest. That is, variables like <em>ID</em> and the <em>prop_miss</em> and <em>nmiss</em> variables we created will interfere with an accurate assessment of missingness. I will update our df to eliminate these.</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="score.html#cb41-1" aria-hidden="true" tabindex="-1"></a>scrub_df <span class="ot">&lt;-</span> scrub_df <span class="sc">%&gt;%</span></span>
<span id="cb41-2"><a href="score.html#cb41-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span> (<span class="sc">-</span><span class="fu">c</span>(ID, nmiss, prop_miss))<span class="co">#further update to exclude the n_miss and prop_miss variables</span></span></code></pre></div>
<p>Missing data analysis commonly looks at proportions by:</p>
<ul>
<li>the entire df</li>
<li>rows/cases/people</li>
</ul>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="score.html#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages(&quot;formattable&quot;)</span></span>
<span id="cb42-2"><a href="score.html#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(formattable)</span>
<span id="cb42-3"><a href="score.html#cb42-3" aria-hidden="true" tabindex="-1"></a>CellsMiss <span class="ot">&lt;-</span> <span class="fu">percent</span>(<span class="fu">mean</span>(<span class="fu">is.na</span>(scrub_df)))<span class="co">#what proportion of cells missing across entire dataset</span></span>
<span id="cb42-4"><a href="score.html#cb42-4" aria-hidden="true" tabindex="-1"></a>CaseComplete <span class="ot">&lt;-</span> <span class="fu">percent</span>(<span class="fu">mean</span>(<span class="fu">complete.cases</span>(scrub_df)))<span class="co">#what proportion of cases (rows) are complete (nonmissing)</span></span>
<span id="cb42-5"><a href="score.html#cb42-5" aria-hidden="true" tabindex="-1"></a>CellsMiss</span></code></pre></div>
<pre><code>## [1] 4.39%</code></pre>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="score.html#cb44-1" aria-hidden="true" tabindex="-1"></a>CaseComplete</span></code></pre></div>
<pre><code>## [1] 79.31%</code></pre>
<p>CUMULATIVE CAPTURE FOR WRITING IT UP: Across cases that were deemed eligible on the basis of the inclusion/exclusion criteria, missingness ranged from 0 to 36.3636364. Across the dataset, 4.39% of cells had missing data and 79.31% of cases had nonmissing data.</p>
</div>
<div id="analyzing-missing-data-patterns" class="section level3" number="3.5.2">
<h3><span class="header-section-number">3.5.2</span> Analyzing Missing Data Patterns</h3>
<p>One approach to analyzing missing data is to assess patterns of missingness. LECTURE? SOMEWHERE?</p>
<p>Several R packages are popularly used for conducting such analyse. In the <em>mice</em> package, <em>md.pattern()</em> function provides a matrix with the number of columns + 1, in which each row corresponds to a missing data pattern (1 = observed, 0 = missing).</p>
<p>Rows and columns are sorted in increasing amounts of missing information.</p>
<p>The last column and row contain row and column counts, respectively.</p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="score.html#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Using the package: mice</span></span>
<span id="cb46-2"><a href="score.html#cb46-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mice)</span>
<span id="cb46-3"><a href="score.html#cb46-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-4"><a href="score.html#cb46-4" aria-hidden="true" tabindex="-1"></a>mice_out <span class="ot">&lt;-</span> <span class="fu">md.pattern</span>(scrub_df, <span class="at">plot =</span> <span class="cn">TRUE</span>, <span class="at">rotate.names =</span> <span class="cn">TRUE</span>)</span>
<span id="cb46-5"><a href="score.html#cb46-5" aria-hidden="true" tabindex="-1"></a>mice_out</span>
<span id="cb46-6"><a href="score.html#cb46-6" aria-hidden="true" tabindex="-1"></a><span class="fu">write.csv</span> (mice_out, <span class="at">file=</span><span class="st">&quot;mice_out.csv&quot;</span>) <span class="co">#optional to write it to a .csv file</span></span></code></pre></div>
<p>The table lets you look at each missing pattern and see which variable(s) is/are missing. The output is in the form of a table that indicates the frequency of each pattern of missingness. Because I haven’t (yet) figured out how to pipe objects from this table into the chapter, this text may dier from the patterns in the current data frame.</p>
<p>Each row in the table represents a different pattern of missingness. At the time of writing, there are 5 patterns of missing data. The patterns are listed in descending order of the least amount of missingness. The most common pattern (23 cases, top row) is one with no missing data. One cases (is missing three cells – three of the items assessing the campus climate for Black students, and so forth.</p>
<p>In general, the data patterns represented a haphazard patterns of responding <span class="citation">(<a href="score.html#ref-enders_applied_2010" role="doc-biblioref">Enders, 2010</a>)</span>.</p>
</div>
<div id="missing-mechanisms" class="section level3" number="3.5.3">
<h3><span class="header-section-number">3.5.3</span> Missing Mechanisms</h3>
<p>Remember Little’s MCAR test. Recently it has a history of appearing, working with glitches, disappearing, and so forth. At the present time I cannot find a package that is working well. When I do, I will add this section.</p>
</div>
</div>
<div id="scoring" class="section level2" number="3.6">
<h2><span class="header-section-number">3.6</span> Scoring</h2>
<p>So let’s get to work to score up the measures for our analysis. Each step of this should involve careful cross-checking with the <a href="./Rate-a-Course_Codebook.pdf">codebook</a>.</p>
<div id="reverse-scoring" class="section level3" number="3.6.1">
<h3><span class="header-section-number">3.6.1</span> Reverse scoring</h3>
<p>As we discovered previously, in the scale that assesses campus climate (higher scores reflect a more negative climate) one of our items (Blst_1, “My <em>institution</em> provides a supportive environment for Black students.”) requires reverse-coding.</p>
<p>To rescore:</p>
<ul>
<li>Create a <em>new</em> variable (this is essential) that is designated as the reversed item. We might put a the letter “r” (for reverse scoring) at the beginning or end: rBlst_1 or Blst_1r. It does not matter; just be consistent.
<ul>
<li>We don’t reverse score into the same variable because when you rerun the script, it just re-reverses the reversed score…into infinity. It’s very easy to lose your place.</li>
</ul></li>
<li>The reversal is an <em>equation</em> where you subtract the value in the item from the range/scaling + 1. For the our three items we subtract each item’s value from 8.</li>
</ul>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="score.html#cb47-1" aria-hidden="true" tabindex="-1"></a>scrub_df<span class="ot">&lt;-</span> scrub_df <span class="sc">%&gt;%</span></span>
<span id="cb47-2"><a href="score.html#cb47-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">rBlst_1 =</span> <span class="dv">8</span> <span class="sc">-</span> Blst_1) <span class="co">#if you had multiple items, you could add a pipe (%&gt;%) at the end of the line and add more until the last one</span></span></code></pre></div>
<p>Per Parent <span class="citation">(<a href="score.html#ref-parent_handling_2013" role="doc-biblioref">2013</a>)</span> we will analyze missingness for each scale, separately.</p>
<ul>
<li>We will calculate scale scores on each scale separately when 80% (roughly) of the data is present.
<ul>
<li>this is somewhat arbitrary, on 4 item scales, I would choose 75% (to allow one to be missing)</li>
<li>on the 3 item scale, I will allow one item to be missing (65%)</li>
</ul></li>
<li>After calculating the scale scores, we will return to analyzing the missingness, looking at the whole df</li>
</ul>
<p>The <em>mean_n()</em> function of <em>sjstats</em> package has allows you to specify how many items (whole number) or what percentage of items should be present in order to get the mean. First, though, we should identify the variables (properly formatted, if rescoring was needed) that should be included in the calculation of each scale and subscale.</p>
<p>In our case, the scale assessing belonging <span class="citation">(<a href="score.html#ref-bollen_perceived_1990" role="doc-biblioref">Bollen &amp; Hoyle, 1990</a>; <a href="score.html#ref-hurtado_effects_1997" role="doc-biblioref">Hurtado &amp; Carter, 1997</a>)</span> involves three items with no reversals. Our campus climate scale was adapted from Szymanski et al.’s LGBTQ College Campus Climate Scale <span class="citation">(<a href="score.html#ref-szymanski_perceptions_2020" role="doc-biblioref">Szymanski &amp; Bissonette, 2020</a>)</span>. While it has not been psychometrically evaluated for the purpose for which I am using it, I will follow the scoring structure in the journal article that introduces the measure. Specifically, the factor structure permits a total scale score and two subscales representing the college response and stigma.</p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="score.html#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sjstats)</span>
<span id="cb48-2"><a href="score.html#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="co">#Making the list of variables</span></span>
<span id="cb48-3"><a href="score.html#cb48-3" aria-hidden="true" tabindex="-1"></a>Belonging_vars <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&#39;Belong_1&#39;</span>,<span class="st">&#39;Belong_2&#39;</span>,<span class="st">&#39;Belong_3&#39;</span>)</span>
<span id="cb48-4"><a href="score.html#cb48-4" aria-hidden="true" tabindex="-1"></a>ResponseBL_vars <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&#39;rBlst_1&#39;</span>, <span class="st">&#39;Blst_4&#39;</span>,<span class="st">&#39;Blst_6&#39;</span>)</span>
<span id="cb48-5"><a href="score.html#cb48-5" aria-hidden="true" tabindex="-1"></a>StigmaBL_vars <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&#39;Blst_2&#39;</span>, <span class="st">&#39;Blst_3&#39;</span>,<span class="st">&#39;Blst_5&#39;</span>)</span>
<span id="cb48-6"><a href="score.html#cb48-6" aria-hidden="true" tabindex="-1"></a>ClimateBL_vars <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&#39;rBlst_1&#39;</span>, <span class="st">&#39;Blst_4&#39;</span>,<span class="st">&#39;Blst_6&#39;</span>,<span class="st">&#39;Blst_2&#39;</span>, <span class="st">&#39;Blst_3&#39;</span>,<span class="st">&#39;Blst_5&#39;</span> )</span>
<span id="cb48-7"><a href="score.html#cb48-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-8"><a href="score.html#cb48-8" aria-hidden="true" tabindex="-1"></a><span class="co">#Creating the new variables</span></span>
<span id="cb48-9"><a href="score.html#cb48-9" aria-hidden="true" tabindex="-1"></a>scrub_df<span class="sc">$</span>Belonging <span class="ot">&lt;-</span> <span class="fu">mean_n</span>(scrub_df[,Belonging_vars], .<span class="dv">65</span>)</span>
<span id="cb48-10"><a href="score.html#cb48-10" aria-hidden="true" tabindex="-1"></a>scrub_df<span class="sc">$</span>ResponseBL <span class="ot">&lt;-</span> <span class="fu">mean_n</span>(scrub_df[,ResponseBL_vars], .<span class="dv">80</span>)</span>
<span id="cb48-11"><a href="score.html#cb48-11" aria-hidden="true" tabindex="-1"></a>scrub_df<span class="sc">$</span>StigmaBL <span class="ot">&lt;-</span> <span class="fu">mean_n</span>(scrub_df[,StigmaBL_vars], .<span class="dv">80</span>)</span>
<span id="cb48-12"><a href="score.html#cb48-12" aria-hidden="true" tabindex="-1"></a>scrub_df<span class="sc">$</span>ClimateBL <span class="ot">&lt;-</span> <span class="fu">mean_n</span>(scrub_df[,ClimateBL_vars], .<span class="dv">80</span>)</span></code></pre></div>
<p>Later it will be helpful to have a df with the item and scale-level variables. Let’s save our <em>scrub_df</em> data for this and write it as an outfile.</p>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="score.html#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write.table</span>(scrub_df, <span class="at">file=</span><span class="st">&quot;BlStItmsScrs210320.csv&quot;</span>, <span class="at">sep=</span><span class="st">&quot;,&quot;</span>, <span class="at">col.names=</span><span class="cn">TRUE</span>, <span class="at">row.names=</span><span class="cn">FALSE</span>)</span></code></pre></div>
</div>
</div>
<div id="missing-analysis-scale-level" class="section level2" number="3.7">
<h2><span class="header-section-number">3.7</span> Missing Analysis: Scale level</h2>
<p>Let’s return to analyzing the missingness, this time including the <em>scale level</em> variables (without the individual items) that will be in our statistical model(s).</p>
<div class="figure">
<img src="images/Ch02/wrkflow_scale_lvl.jpg" alt="" />
<p class="caption">An image of our stage in the workflow for scrubbing and scoring data.</p>
</div>
<p>First let’s get the df down to the variables we want to retain:</p>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="score.html#cb50-1" aria-hidden="true" tabindex="-1"></a>scored <span class="ot">&lt;-</span>(<span class="fu">select</span> (scrub_df, iBIPOC_pr, cmBlack, Belonging, ResponseBL, StigmaBL, ClimateBL))</span>
<span id="cb50-2"><a href="score.html#cb50-2" aria-hidden="true" tabindex="-1"></a>ScoredCaseMiss <span class="ot">&lt;-</span> <span class="fu">nrow</span>(scored) <span class="co">#I produced this object for the sole purpose of feeding the number of cases into the inline text, below</span></span></code></pre></div>
<p>CUMULATIVE CAPTURE FOR WRITING IT UP: Across the 29…</p>
<p>Before we start our formal analysis of missingness at the scale level, let’s continue to scrub by eliminating cases that clearly won’t remain. In the script below we create a variable that counts the number of missing variables and then creates a proportion by dividing it by the number of total variables.</p>
<p>Using the <em>describe()</em> function from the <em>psych</em> package, we can investigate this variable.</p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="score.html#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Create a variable (n_miss) that counts the number missing</span></span>
<span id="cb51-2"><a href="score.html#cb51-2" aria-hidden="true" tabindex="-1"></a>scored<span class="sc">$</span>n_miss <span class="ot">&lt;-</span> scored<span class="sc">%&gt;%</span></span>
<span id="cb51-3"><a href="score.html#cb51-3" aria-hidden="true" tabindex="-1"></a><span class="fu">select</span>(iBIPOC_pr<span class="sc">:</span>ClimateBL) <span class="sc">%&gt;%</span> </span>
<span id="cb51-4"><a href="score.html#cb51-4" aria-hidden="true" tabindex="-1"></a>is.na <span class="sc">%&gt;%</span> </span>
<span id="cb51-5"><a href="score.html#cb51-5" aria-hidden="true" tabindex="-1"></a>rowSums</span>
<span id="cb51-6"><a href="score.html#cb51-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-7"><a href="score.html#cb51-7" aria-hidden="true" tabindex="-1"></a><span class="co">#Create a proportion missing by dividing n_miss by the total number of variables (80)</span></span>
<span id="cb51-8"><a href="score.html#cb51-8" aria-hidden="true" tabindex="-1"></a><span class="co">#Pipe to sort in order of descending frequency to get a sense of the missingness</span></span>
<span id="cb51-9"><a href="score.html#cb51-9" aria-hidden="true" tabindex="-1"></a>scored<span class="ot">&lt;-</span> scored<span class="sc">%&gt;%</span></span>
<span id="cb51-10"><a href="score.html#cb51-10" aria-hidden="true" tabindex="-1"></a><span class="fu">mutate</span>(<span class="at">prop_miss =</span> (n_miss<span class="sc">/</span><span class="dv">6</span>)<span class="sc">*</span><span class="dv">100</span>)<span class="sc">%&gt;%</span></span>
<span id="cb51-11"><a href="score.html#cb51-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(n_miss))</span>
<span id="cb51-12"><a href="score.html#cb51-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-13"><a href="score.html#cb51-13" aria-hidden="true" tabindex="-1"></a>ScoredPrMiss <span class="ot">&lt;-</span> psych<span class="sc">::</span><span class="fu">describe</span>(scored<span class="sc">$</span>prop_miss)</span>
<span id="cb51-14"><a href="score.html#cb51-14" aria-hidden="true" tabindex="-1"></a>ScoredPrMiss <span class="co">#this object is displayed below and I use input from  it for the inline text used in the write-up</span></span></code></pre></div>
<pre><code>##    vars  n mean    sd median trimmed mad min   max range skew kurtosis   se
## X1    1 29  4.6 10.82      0    2.67   0   0 33.33 33.33 1.97     2.29 2.01</code></pre>
<p>CUMULATIVE CAPTURE FOR WRITING IT UP: Across the 29 cases for which the scoring protocol was applied, missingness ranged from 0 to 33.3333333.</p>
<p>We need to decide what is our retention threshhold. Twenty percent seems to be a general rule of thumb. Let’s delete all cases with missingness at 20% or greater.</p>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="score.html#cb53-1" aria-hidden="true" tabindex="-1"></a>scored <span class="ot">&lt;-</span> <span class="fu">filter</span>(scored, prop_miss <span class="sc">&lt;=</span> <span class="dv">20</span>)  <span class="co">#update df to have only those with at least 20% of complete data (this is an arbitrary decision)</span></span>
<span id="cb53-2"><a href="score.html#cb53-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-3"><a href="score.html#cb53-3" aria-hidden="true" tabindex="-1"></a>scored <span class="ot">&lt;-</span>(<span class="fu">select</span> (scored, iBIPOC_pr<span class="sc">:</span>ClimateBL)) <span class="co">#the variable selection just lops off the proportion missing</span></span>
<span id="cb53-4"><a href="score.html#cb53-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-5"><a href="score.html#cb53-5" aria-hidden="true" tabindex="-1"></a>ScoredCasesIncluded <span class="ot">&lt;-</span> <span class="fu">nrow</span>(scored)</span>
<span id="cb53-6"><a href="score.html#cb53-6" aria-hidden="true" tabindex="-1"></a>ScoredCasesIncluded <span class="co">#this object is displayed below and I use input from  it for the inline text used in the write-up</span></span></code></pre></div>
<pre><code>## [1] 26</code></pre>
<p>CUMULATIVE CAPTURE FOR WRITING IT UP: Across the 29 cases for which the scoring protocol was applied, missingness ranged from zero to 33.3333333. After eliminating cases with greater than 20% missing, the dataset analyzed included 26 cases.</p>
<p>With a decision about the number of cases we are going to include, we can continue to analyze missingness.</p>
</div>
<div id="revisiting-missing-analysis-at-the-scale-level" class="section level2" number="3.8">
<h2><span class="header-section-number">3.8</span> Revisiting Missing Analysis at the Scale Level</h2>
<p>We work with a df that includes only the variables in our model. In our case this is easy. In other cases (i.e., maybe there is an ID number) it might be good to create a subset just for this analysis.</p>
<p>Again, we look at missingness as the proportion of</p>
<ul>
<li>individual cells across the dataset, and</li>
<li>rows/cases with nonmissing data</li>
</ul>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="score.html#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(formattable)</span>
<span id="cb55-2"><a href="score.html#cb55-2" aria-hidden="true" tabindex="-1"></a>PrScoredCellsMissing <span class="ot">&lt;-</span><span class="fu">percent</span>(<span class="fu">mean</span>(<span class="fu">is.na</span>(scored))) <span class="co">#percent missing across df</span></span>
<span id="cb55-3"><a href="score.html#cb55-3" aria-hidden="true" tabindex="-1"></a>PrScoredRowsMissing <span class="ot">&lt;-</span> <span class="fu">percent</span>(<span class="fu">mean</span>(<span class="fu">complete.cases</span>(scored))) <span class="co">#percent of rows with nonmissing data</span></span>
<span id="cb55-4"><a href="score.html#cb55-4" aria-hidden="true" tabindex="-1"></a>PrScoredCellsMissing</span></code></pre></div>
<pre><code>## [1] 1.28%</code></pre>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="score.html#cb57-1" aria-hidden="true" tabindex="-1"></a>PrScoredRowsMissing</span></code></pre></div>
<pre><code>## [1] 92.31%</code></pre>
<p>CUMULATIVE CAPTURE FOR WRITING IT UP: Across the 29 cases for which the scoring protocol was applied, missingness ranged from zero to 33.3333333. After eliminating cases with greater than 20% missing, the dataset analyzed included 26 cases. In this dataset we had 1.28% missing across the df; 92.31% of the rows had nonmissing data.</p>
<p><em>At this point in the write-up, if I knew I was going to use a consistent approach for managing data (e.g., listwise or pairwise deletion for ordinary least squares regression, FIML for SEM or CFA) I would mention it here.</em></p>
<p>Let’s look again at missing patterns and mechanisms.</p>
<div id="scale-level-patterns-of-missing-data" class="section level3" number="3.8.1">
<h3><span class="header-section-number">3.8.1</span> Scale Level: Patterns of Missing Data</h3>
<p>Returning to the <em>mice</em> package, we can use the <em>md.pattern()</em> function to examine a matrix with the number of columns + 1 in which each row corresponds to a missing data pattern (1 = observed, 0 = missing). The rows and columns are sorted in increasing amounts of missing information. The last column and row contain row and column counts, respectively.</p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="score.html#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Using the package: mice</span></span>
<span id="cb59-2"><a href="score.html#cb59-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mice)</span></code></pre></div>
<pre><code>## 
## Attaching package: &#39;mice&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:stats&#39;:
## 
##     filter</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     cbind, rbind</code></pre>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="score.html#cb63-1" aria-hidden="true" tabindex="-1"></a>mice_ScaleLvl <span class="ot">&lt;-</span> <span class="fu">md.pattern</span>(scored, <span class="at">plot =</span> <span class="cn">TRUE</span>, <span class="at">rotate.names=</span><span class="cn">TRUE</span>)</span></code></pre></div>
<p><img src="ReC_MultivariateModeling_files/figure-html/scale%20level%20missingness%20w%20mice-1.svg" width="672" /></p>
<p>At the scale-level, this is much easier to interpret. As I am lecturing the results today (the numbers will change) there are only two rows of data because there are only two patterns of missingness. The most common pattern is non-missing data (<em>n</em> = 23). The second pattern occurs when two people have missing data on the <em>iBIPOC_pr</em> variable</p>
</div>
<div id="is-it-mcar" class="section level3" number="3.8.2">
<h3><span class="header-section-number">3.8.2</span> Is it MCAR?</h3>
<p>As noted earlier, I cannot find an MCAR package. This is a placeholder for updating this portion of the lecture when one becomes readily available (and I learn about it)</p>
</div>
<div id="r-eady-for-analysis" class="section level3" number="3.8.3">
<h3><span class="header-section-number">3.8.3</span> R-eady for Analysis</h3>
<p>At this stage the data is ready for analysis. With the AIA approach <span class="citation">(<a href="score.html#ref-parent_handling_2013" role="doc-biblioref">Parent, 2013</a>)</span> the following preliminary analyses would involve pairwise deletion (i.e., the row/case is dropped for that analysis, but included for all others):</p>
<div class="figure">
<img src="images/Ch02/wrkflow_AIAready.jpg" alt="" />
<p class="caption">An image of our stage in the workflow for scrubbing and scoring data.</p>
</div>
<ul>
<li>data diagnostics
<ul>
<li>psychometric properties of scales, such as alpha coefficients</li>
<li>assessing assumptions such as univariate and multivariate normality, outliers, etc.</li>
</ul></li>
<li>preliminary analyses
<ul>
<li>descriptives (means/standard deviations, frequencies)</li>
<li>correlation matrices</li>
</ul></li>
</ul>
<p>AIA can also be used with primary analyses. Examples of how to manage missingness include:</p>
<ul>
<li>ANOVA/regression models
<ul>
<li>if completed with ordinary least squares, pairwise deletion would be utilized</li>
</ul></li>
<li>SEM/CFA models with observed, latent, or hybrid models
<ul>
<li>if FIML (we’ll discuss later) is specified, all cases are used, even when there is missingness</li>
</ul></li>
<li>EFA models
<ul>
<li>these can handle item-level missingness</li>
</ul></li>
<li>Hierarchical linear modeling/multilevel modeling/mixed effects modeling
<ul>
<li>While all data needs to be present for a given cluster/wave, it is permissible to have varying numbers of clusters/waves per case</li>
</ul></li>
</ul>
</div>
</div>
<div id="the-apa-style-write-up" class="section level2" number="3.9">
<h2><span class="header-section-number">3.9</span> The APA Style Write-Up</h2>
</div>
<div id="results" class="section level2" number="3.10">
<h2><span class="header-section-number">3.10</span> Results</h2>
<p>All analyses were completed in R Studio (v. 1.4.1106) with R (v. 4.0.4).</p>
<p><strong>Missing Data Analysis and Treatment of Missing Data</strong></p>
<p>Available item analysis (AIA; <span class="citation">(<a href="score.html#ref-parent_handling_2013" role="doc-biblioref">Parent, 2013</a>)</span>) is a strategy for managing missing data that uses available data for analysis and excludes cases with missing data points only for analyses in which the data points would be directly involved. Parent (2013) suggested that AIA is equivalent to more complex methods (e.g., multiple imputation) across a number of variations of sample size, magnitude of associations among items, and degree of missingness. Thus, we utilized Parent’s recommendations to guide our approach to managing missing data. Missing data analyses were conducted with tools in base R as well as the R packages, <em>psych</em> (v. 1.0.12) and <em>mice</em> (v. 3.13.0).</p>
<p>Across cases that were deemed eligible on the basis of the inclusion/exclusion criteria, missingness ranged from 0 to 36.3636364. Across the dataset, 4.39% of cells had missing data and 79.31% of cases had nonmissing data. At this stage in the analysis, we allowed all cases with less than 90% missing to continue to the scoring stage. Guided by Parent’s <span class="citation">(<a href="score.html#ref-parent_handling_2013" role="doc-biblioref">2013</a>)</span> AIA approach, scales with three items were scored if at least two items were non-missing; the scale with 4 items was scored if it at least three non-missig items; and the scale with six items was scored if it had at least five non-missing items. Across the 29 cases for which the scoring protocol was applied, missingness ranged from 0 to 33.3333333. After eliminating cases with greater than 20% missing, the dataset analyzed included <code>ScoredCasesIncluded</code> cases. In this dataset 1.28% was missing across the df; 92.31% of the rows had nonmissing data.</p>
<p>Given that our sample sizes were reasonable for the planned analyses and the degree of missingness was low, we specified a …. (and here we would say how we analyzed the data: AIA/pairwise deletion, FIML, multiply imputed at the scale level…stay tuned.)</p>
</div>
<div id="practice-problems-1" class="section level2" number="3.11">
<h2><span class="header-section-number">3.11</span> Practice Problems</h2>
<p>The three problems described below are designed to be continuations from the previous chapter (Scrubbing).</p>
<div id="problem-1-reworking-the-chapter-problem" class="section level3" number="3.11.1">
<h3><span class="header-section-number">3.11.1</span> Problem #1: Reworking the Chapter Problem</h3>
<p>If you chose this option in the prior chapter, you imported the data from Qualtrics, applied inclusion/exclusion criteria, renamed variables, downsized the df to the variables of interest, and wrote up the preliminary results.</p>
<p>Continue working with this data to:</p>
<table>
<colgroup>
<col width="76%" />
<col width="12%" />
<col width="11%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Assignment Component</th>
<th align="center"></th>
<th align="center"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">1. Proper formatting of your the variable representing the proportion of BIPOC instructor</td>
<td align="center">5</td>
<td align="center">_____</td>
</tr>
<tr class="even">
<td align="left">2. Proper formatting of your the variable representing the</td>
<td align="center">5</td>
<td align="center">_____</td>
</tr>
<tr class="odd">
<td align="left">3. Proper formatting of variables that will be used in the scales/subscales</td>
<td align="center">5</td>
<td align="center">_____</td>
</tr>
<tr class="even">
<td align="left">4. Evaluate and interpret item-level missingness</td>
<td align="center">5</td>
<td align="center">_____</td>
</tr>
<tr class="odd">
<td align="left">5. Score any scales/subscales</td>
<td align="center">5</td>
<td align="center">_____</td>
</tr>
<tr class="even">
<td align="left">6. Evaluate and interpret scale-level missingness</td>
<td align="center">5</td>
<td align="center">_____</td>
</tr>
<tr class="odd">
<td align="left">7. Represent your work in an APA-style write-up (added to the writeup in the previous chapter)</td>
<td align="center">5</td>
<td align="center">_____</td>
</tr>
<tr class="even">
<td align="left">8. Explanation to grader</td>
<td align="center">5</td>
<td align="center">_____</td>
</tr>
<tr class="odd">
<td align="left"><strong>Totals</strong></td>
<td align="center">40</td>
<td align="center">_____</td>
</tr>
</tbody>
</table>
</div>
<div id="problem-2-use-the-rate-a-recent-course-survey-choosing-different-variables-1" class="section level3" number="3.11.2">
<h3><span class="header-section-number">3.11.2</span> Problem #2: Use the <em>Rate-a-Recent-Course</em> Survey, Choosing Different Variables</h3>
<p>If you chose this option in the prior chapter, you chose a minimum of three variables from the <em>Rate-a-Recent-Course</em> survey to include in a simple statistical model. You imported the dat from Qualtrics, applied inclusion/exclusion criteria, renamed variables, downsized the df to the variables of interest and wrote up the preliminary results.</p>
<p>Continue working with this data to:</p>
<table>
<colgroup>
<col width="76%" />
<col width="12%" />
<col width="11%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Assignment Component</th>
<th align="center">Points Possible</th>
<th align="center">Points Earned</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">1. Proper formatting of your first variable</td>
<td align="center">5</td>
<td align="center">_____</td>
</tr>
<tr class="even">
<td align="left">2. Proper formatting of your second variable</td>
<td align="center">5</td>
<td align="center">_____</td>
</tr>
<tr class="odd">
<td align="left">3. Proper formatting of your third variable</td>
<td align="center">5</td>
<td align="center">_____</td>
</tr>
<tr class="even">
<td align="left">4. Evaluate and interpret item-level missingness</td>
<td align="center">5</td>
<td align="center">_____</td>
</tr>
<tr class="odd">
<td align="left">5. Score any scales/subscales</td>
<td align="center">5</td>
<td align="center">_____</td>
</tr>
<tr class="even">
<td align="left">6. Evaluate and interpret scale-level missingness</td>
<td align="center">5</td>
<td align="center">_____</td>
</tr>
<tr class="odd">
<td align="left">7. Represent your work in an APA-style write-up (added to the writeup in the previous chapter)</td>
<td align="center">5</td>
<td align="center">_____</td>
</tr>
<tr class="even">
<td align="left">8. Explanation to grader</td>
<td align="center">5</td>
<td align="center">_____</td>
</tr>
<tr class="odd">
<td align="left"><strong>Totals</strong></td>
<td align="center">40</td>
<td align="center">_____</td>
</tr>
</tbody>
</table>
</div>
<div id="problem-3-other-data-1" class="section level3" number="3.11.3">
<h3><span class="header-section-number">3.11.3</span> Problem #3: Other data</h3>
<p>If you chose this option in the prior chapter, you used raw data that was available to you. You imported it into R, applied inclusion/exclusion criteria, renamed variables, downsized the df to the variables of interest, and wrote up the preliminary results.</p>
<p>Continue working with this data to:</p>
<table>
<colgroup>
<col width="76%" />
<col width="12%" />
<col width="11%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Assignment Component</th>
<th align="center">Points Possible</th>
<th align="center">Points Earned</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">1. Proper formatting of variables of interest (at least three)</td>
<td align="center">15</td>
<td align="center">_____</td>
</tr>
<tr class="even">
<td align="left">2. Evaluate and interpret item-level missingness</td>
<td align="center">5</td>
<td align="center">_____</td>
</tr>
<tr class="odd">
<td align="left">3. Score any scales/subscales</td>
<td align="center">5</td>
<td align="center">_____</td>
</tr>
<tr class="even">
<td align="left">4. Evaluate and interpret scale-level missingness</td>
<td align="center">5</td>
<td align="center">_____</td>
</tr>
<tr class="odd">
<td align="left">5. Represent your work in an APA-style write-up (added to the writeup in the previous chapter)</td>
<td align="center">5</td>
<td align="center">_____</td>
</tr>
<tr class="even">
<td align="left">6. Explanation to grader</td>
<td align="center">5</td>
<td align="center">_____</td>
</tr>
<tr class="odd">
<td align="left"><strong>Totals</strong></td>
<td align="center">40</td>
<td align="center">_____</td>
</tr>
</tbody>
</table>
</div>
</div>
<div id="bonus-reel" class="section level2" number="3.12">
<h2><span class="header-section-number">3.12</span> Bonus Reel:</h2>
<div class="figure">
<img src="images/film-strip-1.jpg" id="id" class="class" width="620" height="211" alt="" />
<p class="caption">Image of a filmstrip signifying that the what follows is considered to be supplemental</p>
</div>
</div>
<div id="references-1" class="section level2" number="3.13">
<h2><span class="header-section-number">3.13</span> References</h2>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="score.html#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sessionInfo</span>()</span></code></pre></div>
<pre><code>## R version 4.0.4 (2021-02-15)
## Platform: x86_64-w64-mingw32/x64 (64-bit)
## Running under: Windows 10 x64 (build 18362)
## 
## Matrix products: default
## 
## locale:
## [1] LC_COLLATE=English_United States.1252 
## [2] LC_CTYPE=English_United States.1252   
## [3] LC_MONETARY=English_United States.1252
## [4] LC_NUMERIC=C                          
## [5] LC_TIME=English_United States.1252    
## 
## attached base packages:
## [1] stats     graphics  grDevices utils     datasets  methods   base     
## 
## other attached packages:
##  [1] gdtools_0.2.2     mice_3.13.0       sjstats_0.18.0    formattable_0.2.1
##  [5] forcats_0.5.0     stringr_1.4.0     dplyr_1.0.2       purrr_0.3.4      
##  [9] readr_1.4.0       tidyr_1.1.2       tibble_3.0.4      ggplot2_3.3.3    
## [13] tidyverse_1.3.0   qualtRics_3.1.4  
## 
## loaded via a namespace (and not attached):
##  [1] nlme_3.1-151      fs_1.5.0          lubridate_1.7.9.2 insight_0.11.1   
##  [5] httr_1.4.2        tools_4.0.4       backports_1.2.0   R6_2.5.0         
##  [9] sjlabelled_1.1.7  DBI_1.1.0         colorspace_2.0-0  withr_2.3.0      
## [13] tidyselect_1.1.0  mnormt_2.0.2      emmeans_1.5.3     curl_4.3         
## [17] compiler_4.0.4    performance_0.6.1 cli_2.2.0         rvest_0.3.6      
## [21] xml2_1.3.2        sandwich_3.0-0    bookdown_0.21     bayestestR_0.8.0 
## [25] scales_1.1.1      mvtnorm_1.1-1     psych_2.0.12      systemfonts_0.3.2
## [29] digest_0.6.27     minqa_1.2.4       svglite_1.2.3.2   rmarkdown_2.6    
## [33] pkgconfig_2.0.3   htmltools_0.5.0   lme4_1.1-26       dbplyr_2.0.0     
## [37] htmlwidgets_1.5.3 rlang_0.4.9       readxl_1.3.1      rstudioapi_0.13  
## [41] generics_0.1.0    zoo_1.8-8         jsonlite_1.7.2    magrittr_2.0.1   
## [45] parameters_0.10.1 Matrix_1.2-18     Rcpp_1.0.5        munsell_0.5.0    
## [49] fansi_0.4.1       lifecycle_0.2.0   stringi_1.5.3     multcomp_1.4-15  
## [53] yaml_2.2.1        MASS_7.3-53       grid_4.0.4        parallel_4.0.4   
## [57] sjmisc_2.8.5      crayon_1.3.4      lattice_0.20-41   haven_2.3.1      
## [61] splines_4.0.4     hms_0.5.3         tmvnsim_1.0-2     knitr_1.30       
## [65] pillar_1.4.7      boot_1.3-25       estimability_1.3  effectsize_0.4.1 
## [69] codetools_0.2-18  reprex_0.3.0      glue_1.4.2        evaluate_0.14    
## [73] modelr_0.1.8      vctrs_0.3.6       nloptr_1.2.2.2    cellranger_1.1.0 
## [77] gtable_0.3.0      assertthat_0.2.1  xfun_0.19         xtable_1.8-4     
## [81] broom_0.7.3       coda_0.19-4       survival_3.2-7    statmod_1.4.35   
## [85] TH.data_1.0-10    ellipsis_0.3.1</code></pre>

<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-adames_fallacy_2021" class="csl-entry">
Adames, H. Y., Chavez-Dueñas, N. Y., &amp; Jernigan, M. M. (2021). The fallacy of a raceless <span>Latinidad</span>: <span>Action</span> guidelines for centering <span>Blackness</span> in <span>Latinx</span> psychology. <em>Journal of Latinx Psychology</em>, <em>9</em>(1), 26–44. <a href="https://doi.org/10.1037/lat0000179">https://doi.org/10.1037/lat0000179</a>
</div>
<div id="ref-bollen_perceived_1990" class="csl-entry">
Bollen, K. A., &amp; Hoyle, R. H. (1990). Perceived cohesion: <span>A</span> conceptual and empirical examination. <em>Social Forces</em>, <em>69</em>(2), 479–504. <a href="https://doi.org/10.2307/2579670">https://doi.org/10.2307/2579670</a>
</div>
<div id="ref-capielo_rosario_acculturation_2019" class="csl-entry">
Capielo Rosario, C., Adames, H. Y., Chavez-Dueñas, N. Y., &amp; Renteria, R. (2019). Acculturation <span>Profiles</span> of <span>Central</span> <span>Florida</span> <span>Puerto</span> <span>Ricans</span>: <span>Examining</span> the <span>Influence</span> of <span>Skin</span> <span>Color</span>, <span>Perceived</span> <span>Ethnic</span>-<span>Racial</span> <span>Discrimination</span>, and <span>Neighborhood</span> <span>Ethnic</span>-<span>Racial</span> <span>Composition</span>. <em>Journal of Cross-Cultural Psychology</em>, <em>50</em>(4), 556–576. <a href="https://doi.org/10.1177/0022022119835979">https://doi.org/10.1177/0022022119835979</a>
</div>
<div id="ref-enders_applied_2010" class="csl-entry">
Enders, C. K. (2010). <em>Applied missing data analysis</em>. Guilford Press.
</div>
<div id="ref-field_discovering_2012" class="csl-entry">
Field, A. P. (2012). <em>Discovering statistics using <span>R</span></em>. Sage.
</div>
<div id="ref-hurtado_linking_2007" class="csl-entry">
Hurtado, S. (2007). Linking <span>Diversity</span> with the <span>Educational</span> and <span>Civic</span> <span>Missions</span> of <span>Higher</span> <span>Education</span>. <em>Review of Higher Education: Journal of the Association for the Study of Higher Education</em>, <em>30</em>(2), 185–196. <a href="https://doi.org/10.1353/rhe.2006.0070">https://doi.org/10.1353/rhe.2006.0070</a>
</div>
<div id="ref-hurtado_effects_1997" class="csl-entry">
Hurtado, S., &amp; Carter, D. F. (1997). Effects of college transition and perceptions of the campus racial climate on <span>Latino</span> college students’ sense of belonging. <em>Sociology of Education</em>, <em>70</em>, 324–345. <a href="https://doi.org/10.2307/2673270">https://doi.org/10.2307/2673270</a>
</div>
<div id="ref-iacovino_retaining_2016" class="csl-entry">
Iacovino, J. M., &amp; James, S. A. (2016). Retaining <span>Students</span> of <span>Color</span> in <span>Higher</span> <span>Education</span>: <span>Expanding</span> <span>Our</span> <span>Focus</span> to <span>Psychosocial</span> <span>Adjustment</span> and <span>Mental</span> <span>Health</span>. In <em>The <span>Crisis</span> of <span>Race</span> in <span>Higher</span> <span>Education</span>: <span>A</span> <span>Day</span> of <span>Discovery</span> and <span>Dialogue</span></em> (Vol. 19, pp. 61–84). Emerald Group Publishing Limited. <a href="https://doi.org/10.1108/S1479-364420160000019004">https://doi.org/10.1108/S1479-364420160000019004</a>
</div>
<div id="ref-kim_yes_2021" class="csl-entry">
Kim, P. (2021). Yes, <span>Asians</span> and <span>Asian</span> <span>Americans</span> experience racism. In <em>The Seattle Times</em>. <a href="https://www.seattletimes.com/opinion/yes-asians-and-asian-americans-experience-racism/">https://www.seattletimes.com/opinion/yes-asians-and-asian-americans-experience-racism/</a>
</div>
<div id="ref-kim_guest_2021" class="csl-entry">
Kim, P. Y. (2021). Guest <span>Post</span>: <span>Anti</span>-<span>Asian</span> <span>Racism</span> during the <span>Pandemic</span>: <span>How</span> <span>Faculty</span> on <span>Christian</span> <span>Campuses</span> <span>Can</span> <span>Support</span> <span>Asian</span> and <span>Asian</span> <span>American</span> <span>Students</span>. In <em>Christian Scholar’s Review</em>. <a href="https://christianscholars.com/guest-post-anti-asian-racism-during-the-pandemic-how-faculty-on-christian-campuses-can-support-asian-and-asian-american-students/">https://christianscholars.com/guest-post-anti-asian-racism-during-the-pandemic-how-faculty-on-christian-campuses-can-support-asian-and-asian-american-students/</a>
</div>
<div id="ref-kline_principles_2016" class="csl-entry">
Kline, R. B. (2016). <em>Principles and practice of structural equation modeling</em> (4th ed.). Guilford Publications. <a href="http://ebookcentral.proquest.com/lib/spu/detail.action?docID=4000663">http://ebookcentral.proquest.com/lib/spu/detail.action?docID=4000663</a>
</div>
<div id="ref-lewis_black_2019" class="csl-entry">
Lewis, K. R., &amp; Shah, P. P. (2019). Black students’ narratives of diversity and inclusion initiatives and the campus racial climate: <span>An</span> interest-convergence analysis. <em>Journal of Diversity in Higher Education</em>. <a href="https://doi.org/10.1037/dhe0000147">https://doi.org/10.1037/dhe0000147</a>
</div>
<div id="ref-little_statistical_2002" class="csl-entry">
Little, R. J. A., &amp; Rubin, D. B. (2002). <em>Statistical analysis with missing data</em> (Second edition.). Wiley. <a href="http://site.ebrary.com/id/10921256">http://site.ebrary.com/id/10921256</a>
</div>
<div id="ref-mallinckrodt_scientist-practitioner-advocate_2014" class="csl-entry">
Mallinckrodt, B., Miles, J. R., &amp; Levy, J. J. (2014). The scientist-practitioner-advocate model: <span>Addressing</span> contemporary training needs for social justice advocacy. <em>Training and Education in Professional Psychology</em>, <em>8</em>(4), 303–311. <a href="https://doi.org/10.1037/tep0000045">https://doi.org/10.1037/tep0000045</a>
</div>
<div id="ref-mosley_critical_2021" class="csl-entry">
Mosley, D. V., Hargons, C. N., Meiller, C., Angyal, B., Wheeler, P., Davis, C., &amp; Stevens-Watkins, D. (2021). Critical consciousness of anti-<span>Black</span> racism: <span>A</span> practical model to prevent and resist racial trauma. <em>Journal of Counseling Psychology</em>, <em>68</em>(1), 1–16. <a href="https://doi.org/10.1037/cou0000430">https://doi.org/10.1037/cou0000430</a>
</div>
<div id="ref-mosley_radical_2020" class="csl-entry">
Mosley, D. V., Neville, H. A., Chavez‐Dueñas, N. Y., Adames, H. Y., Lewis, J. A., &amp; French, B. H. (2020). Radical hope in revolting times: <span>Proposing</span> a culturally relevant psychological framework. <em>Social and Personality Psychology Compass</em>, <em>14</em>(1). <a href="https://doi.org/10.1111/spc3.12512">https://doi.org/10.1111/spc3.12512</a>
</div>
<div id="ref-parent_handling_2013" class="csl-entry">
Parent, M. C. (2013). Handling item-level missing data: <span>Simpler</span> is just as good. <em>The Counseling Psychologist</em>, <em>41</em>(4), 568–600. <a href="https://doi.org/10.1177/0011000012445176">https://doi.org/10.1177/0011000012445176</a>
</div>
<div id="ref-singh_building_2020" class="csl-entry">
Singh, A. (2020). Building a <span>Counseling</span> <span>Psychology</span> of <span>Liberation</span>: <span>The</span> <span>Path</span> <span>Behind</span> <span>Us</span>, <span>Under</span> <span>Us</span>, and <span>Before</span> <span>Us</span>. <em>The Counseling Psychologist</em>, <em>48</em>(8), 1109–1130. <a href="https://doi.org/10.1177/0011000020959007">https://doi.org/10.1177/0011000020959007</a>
</div>
<div id="ref-noauthor_stop_nodate" class="csl-entry">
<em><span>STOP</span> <span>AAPI</span> <span>HATE</span></em>. (n.d.). Retrieved March 19, 2021, from <a href="https://stopaapihate.org/">https://stopaapihate.org/</a>
</div>
<div id="ref-szymanski_perceptions_2020" class="csl-entry">
Szymanski, D. M., &amp; Bissonette, D. (2020). Perceptions of the <span>LGBTQ</span> <span>College</span> <span>Campus</span> <span>Climate</span> <span>Scale</span>: <span>Development</span> and <span>Psychometric</span> <span>Evaluation</span>. <em>Journal of Homosexuality</em>, <em>67</em>(10), 1412–1428. <a href="https://doi.org/10.1080/00918369.2019.1591788">https://doi.org/10.1080/00918369.2019.1591788</a>
</div>
</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="scrub.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": "https://github.com/ontheline/otl-bookdown/blob/master/03-Scoring.Rmd",
"text": null
},
"download": ["ReC_MultivariateModeling.pdf"],
"toc": {
"collapse": "section",
"scroll_highlight": true
},
"search": true
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
